// Functional-boundary and byte-identity checks for staged M4 packages.

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { basename, join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..", "..");
const SCHEMAS = join(ROOT, "contracts", "schemas", "v1");
const failures: string[] = [];

function sha256(value: string | Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

function filesUnder(directory: string, excluded = new Set<string>()): string[] {
  const files: string[] = [];
  for (const name of readdirSync(directory).sort()) {
    if (name === "__pycache__" || name.endsWith(".pyc")) continue;
    const path = join(directory, name);
    if (statSync(path).isDirectory()) files.push(...filesUnder(path, excluded));
    else if (!excluded.has(name)) files.push(path);
  }
  return files;
}

function identity(directory: string, excluded = new Set<string>()): { bytes: number; files: number; sha256: string } {
  const entries = filesUnder(directory, excluded).map((path) => {
    const bytes = readFileSync(path);
    return [relative(directory, path), bytes.length, sha256(bytes)];
  });
  return {
    bytes: entries.reduce((total, entry) => total + Number(entry[1]), 0),
    files: entries.length,
    sha256: sha256(JSON.stringify(entries)),
  };
}

const packages = [
  { language: "go", trace: "packages/contracts-go/generated/trace.json", directories: ["packages/contracts-go/generated"] },
  { language: "typescript", trace: "packages/contracts-typescript/src/generated/trace.json", directories: ["packages/contracts-typescript/src/generated"] },
  {
    language: "python",
    trace: "packages/contracts-python/anvilkit_contracts/generated/trace.json",
    directories: [
      "packages/contracts-python/anvilkit_contracts/generated",
      "packages/contracts-python/anvilkit_agent_client",
      "packages/contracts-python/anvilkit_pagix_client",
    ],
  },
  {
    language: "java",
    trace: "packages/contracts-java/src/main/resources/META-INF/anvilkit/generation-trace.json",
    directories: ["packages/contracts-java/src/main/java/dev/anvilkit/contracts/generated"],
  },
];

const logicalIds: string[] = [];
const governedValues = new Set<string>();
function collectEnums(value: unknown): void {
  if (Array.isArray(value)) {
    value.forEach(collectEnums);
    return;
  }
  if (value === null || typeof value !== "object") return;
  const object = value as Record<string, unknown>;
  if (Array.isArray(object.enum)) {
    object.enum.filter((item): item is string => typeof item === "string").forEach((item) => governedValues.add(item));
  }
  Object.values(object).forEach(collectEnums);
}

for (const name of readdirSync(SCHEMAS).filter((item) => item.endsWith(".schema.json")).sort()) {
  const schema = JSON.parse(readFileSync(join(SCHEMAS, name), "utf8")) as Record<string, unknown>;
  const metadata = schema["x-anvilkit-contract"] as { logicalId: string };
  logicalIds.push(metadata.logicalId);
  collectEnums(schema);
}

for (const item of packages) {
  const trace = JSON.parse(readFileSync(join(ROOT, item.trace), "utf8"));
  if (trace.language !== item.language) failures.push(`${item.language}: trace language mismatch`);
  const bom = JSON.parse(readFileSync(join(ROOT, "contracts", "governance", "m4", "release-bom.json"), "utf8"));
  if (trace.rootBomState !== "composed-candidate-unpublished" || trace.rootBomIdentity !== bom.digest) failures.push(`${item.language}: BOM trace identity mismatch`);
  const identities = item.directories.map((path) => {
    const excluded = path.endsWith("generated") && item.language !== "java" ? new Set(["trace.json"]) : new Set<string>();
    return { directory: basename(path), ...identity(join(ROOT, path), excluded) };
  });
  const combined = sha256(JSON.stringify(identities));
  if (trace.output.sha256 !== combined) failures.push(`${item.language}: generated byte identity drift`);

  const source = item.directories.flatMap((path) => filesUnder(join(ROOT, path), new Set(["trace.json"])))
    .map((path) => readFileSync(path, "utf8")).join("\n");
  for (const logicalId of logicalIds) {
    if (!source.includes(logicalId)) failures.push(`${item.language}: missing generated ${logicalId}`);
  }
  for (const value of governedValues) {
    if (!source.includes(value)) failures.push(`${item.language}: missing governed wire value ${JSON.stringify(value)}`);
  }
}

if (failures.length > 0) {
  console.error("M4 generated package check FAILED:");
  failures.sort().forEach((failure) => console.error(`  ${failure}`));
  process.exit(1);
}

console.log(`M4 generated packages valid: four languages, ${logicalIds.length} logical contracts, ${governedValues.size} governed enum values, and stable output identities`);
