// Contract codegen pipeline (FR-002, EW-CONTRACT-004).
//
// Reads contracts/events/v1 + contracts/openapi/v1, validates all fixtures,
// and generates Go bindings into services/export-worker/contracts/.
// Deterministic: output depends only on the contract files (no timestamps).
//
// Usage (from the repo root):
//   bun packages/contracts-codegen/generate.ts [--update-lock]

import { createHash } from "node:crypto";
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { spawnSync } from "node:child_process";

const REPO_ROOT = join(import.meta.dir, "..", "..");
const CONTRACTS_DIR = join(REPO_ROOT, "contracts");
const EVENTS_DIR = join(CONTRACTS_DIR, "events", "v1");
const OPENAPI_DIR = join(CONTRACTS_DIR, "openapi", "v1");
const ARTIFACT_DIR = join(CONTRACTS_DIR, "artifact", "v1");
const WORKER_DIR = join(REPO_ROOT, "services", "export-worker");
const GO_CONTRACTS_DIR = join(WORKER_DIR, "contracts");
const LOCK_PATH = join(CONTRACTS_DIR, "contracts.lock.json");

const GENERATED_HEADER = (source: string) =>
  `// Code generated by packages/contracts-codegen/generate.ts from ${source}. DO NOT EDIT.\n`;

// ---------------------------------------------------------------------------
// Minimal JSON Schema (draft 2020-12 subset) validator.
// Supports exactly the keywords used by the contracts in this repository:
// type, properties, required, additionalProperties, enum, const, pattern,
// minLength, minimum, maximum, items, $ref (within one document).
// ---------------------------------------------------------------------------

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };
type Schema = { [k: string]: Json };

function resolveRef(root: Json, ref: string): Schema {
  if (!ref.startsWith("#/")) throw new Error(`unsupported $ref: ${ref}`);
  let node: Json = root;
  for (const part of ref.slice(2).split("/")) {
    if (node === null || typeof node !== "object" || Array.isArray(node)) {
      throw new Error(`$ref not found: ${ref}`);
    }
    node = (node as { [k: string]: Json })[part];
    if (node === undefined) throw new Error(`$ref not found: ${ref}`);
  }
  return node as Schema;
}

function validate(
  schema: Schema,
  value: Json,
  root: Json,
  path: string,
  errors: string[],
): void {
  if (typeof schema.$ref === "string") {
    validate(resolveRef(root, schema.$ref), value, root, path, errors);
    return;
  }
  if ("const" in schema) {
    if (JSON.stringify(value) !== JSON.stringify(schema.const)) {
      errors.push(`${path}: expected const ${JSON.stringify(schema.const)}`);
    }
    return;
  }
  if (Array.isArray(schema.enum)) {
    if (!schema.enum.some((v) => JSON.stringify(v) === JSON.stringify(value))) {
      errors.push(`${path}: value ${JSON.stringify(value)} not in enum`);
      return;
    }
  }
  const type = schema.type;
  if (type === "object") {
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      errors.push(`${path}: expected object`);
      return;
    }
    const obj = value as { [k: string]: Json };
    const props = (schema.properties ?? {}) as { [k: string]: Schema };
    for (const req of (schema.required ?? []) as string[]) {
      if (!(req in obj)) errors.push(`${path}: missing required property ${req}`);
    }
    for (const [key, val] of Object.entries(obj)) {
      if (key in props) {
        validate(props[key], val, root, `${path}.${key}`, errors);
      } else if (schema.additionalProperties === false) {
        errors.push(`${path}: additional property ${key} not allowed`);
      }
    }
    return;
  }
  if (type === "array") {
    if (!Array.isArray(value)) {
      errors.push(`${path}: expected array`);
      return;
    }
    const items = schema.items as Schema | undefined;
    if (items) value.forEach((v, i) => validate(items, v, root, `${path}[${i}]`, errors));
    return;
  }
  if (type === "string") {
    if (typeof value !== "string") {
      errors.push(`${path}: expected string`);
      return;
    }
    if (typeof schema.minLength === "number" && value.length < schema.minLength) {
      errors.push(`${path}: shorter than minLength ${schema.minLength}`);
    }
    if (typeof schema.pattern === "string" && !new RegExp(schema.pattern).test(value)) {
      errors.push(`${path}: does not match pattern ${schema.pattern}`);
    }
    return;
  }
  if (type === "integer" || type === "number") {
    if (typeof value !== "number" || (type === "integer" && !Number.isInteger(value))) {
      errors.push(`${path}: expected ${type}`);
      return;
    }
    if (typeof schema.minimum === "number" && value < schema.minimum) {
      errors.push(`${path}: below minimum ${schema.minimum}`);
    }
    if (typeof schema.maximum === "number" && value > schema.maximum) {
      errors.push(`${path}: above maximum ${schema.maximum}`);
    }
    return;
  }
  if (type === "boolean") {
    if (typeof value !== "boolean") errors.push(`${path}: expected boolean`);
    return;
  }
}

function assertValid(schema: Schema, value: Json, root: Json, label: string): void {
  const errors: string[] = [];
  validate(schema, value, root, "$", errors);
  if (errors.length > 0) {
    throw new Error(`fixture ${label} failed validation:\n  ${errors.join("\n  ")}`);
  }
}

function assertInvalid(schema: Schema, value: Json, root: Json, label: string): void {
  const errors: string[] = [];
  validate(schema, value, root, "$", errors);
  if (errors.length === 0) {
    throw new Error(`invalid fixture ${label} unexpectedly passed validation`);
  }
}

// ---------------------------------------------------------------------------
// Go naming helpers.
// ---------------------------------------------------------------------------

const INITIALISMS = new Set(["id", "url", "uri", "api", "http", "json"]);

function goFieldName(prop: string): string {
  // camelCase property → exported Go field, honoring common initialisms.
  const words = prop
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[\s_.-]+/)
    .filter(Boolean);
  return words
    .map((w) => {
      const lower = w.toLowerCase();
      if (INITIALISMS.has(lower)) return lower.toUpperCase();
      return w.charAt(0).toUpperCase() + w.slice(1);
    })
    .join("");
}

function goConstSuffix(value: string): string {
  // enum value → Go constant name fragment, e.g. RENDER_ORIGIN_5XX → RenderOrigin5xx.
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((tok) => {
      const lower = tok.toLowerCase();
      if (/^[0-9]/.test(lower)) return lower;
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join("");
}

function goArgName(param: string): string {
  const field = goFieldName(param);
  return field.charAt(0).toLowerCase() + field.slice(1);
}

// ---------------------------------------------------------------------------
// Go type emission from schema properties.
// ---------------------------------------------------------------------------

interface EnumSpec {
  goType: string;
  values: string[];
  doc: string;
}

function propGoType(
  prop: string,
  schema: Schema,
  enumTypes: Record<string, string>,
  refNamer: (ref: string) => string,
  typeOverrides: Record<string, string> = {},
): string {
  if (prop in typeOverrides) return typeOverrides[prop];
  if (typeof schema.$ref === "string") return refNamer(schema.$ref);
  if (prop in enumTypes && Array.isArray(schema.enum)) return enumTypes[prop];
  if ("const" in schema) {
    return typeof schema.const === "number" ? "int64" : "string";
  }
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
      return "int64";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "array": {
      const items = schema.items as Schema | undefined;
      if (items && typeof items.$ref === "string") return "[]" + refNamer(items.$ref);
      if (items && items.type === "string") return "[]string";
      throw new Error(`unsupported array items for property ${prop}`);
    }
    default:
      throw new Error(`unsupported schema type for property ${prop}: ${schema.type}`);
  }
}

function emitStruct(
  goName: string,
  doc: string,
  schema: Schema,
  enumTypes: Record<string, string>,
  refNamer: (ref: string) => string,
  fieldRenames: Record<string, string> = {},
  typeOverrides: Record<string, string> = {},
): string {
  const required = new Set((schema.required ?? []) as string[]);
  const props = (schema.properties ?? {}) as { [k: string]: Schema };
  let out = `// ${goName} ${doc}\n`;
  out += `type ${goName} struct {\n`;
  for (const [prop, propSchema] of Object.entries(props)) {
    const goType = propGoType(prop, propSchema, enumTypes, refNamer, typeOverrides);
    const omit = required.has(prop) ? "" : ",omitempty";
    const fieldName = fieldRenames[prop] ?? goFieldName(prop);
    const desc = typeof propSchema.description === "string" ? propSchema.description : "";
    if (desc) out += `\t// ${fieldName}: ${desc.replace(/\n/g, " ")}\n`;
    out += `\t${fieldName} ${goType} \`json:"${prop}${omit}"\`\n`;
  }
  out += "}\n";
  return out;
}

function emitEnum(spec: EnumSpec): string {
  let out = `// ${spec.goType} ${spec.doc}\n`;
  out += `type ${spec.goType} string\n\n`;
  out += `// ${spec.goType} values.\nconst (\n`;
  for (const v of spec.values) {
    out += `\t${spec.goType}${goConstSuffix(v)} ${spec.goType} = "${v}"\n`;
  }
  out += ")\n";
  return out;
}

// ---------------------------------------------------------------------------
// File IO helpers.
// ---------------------------------------------------------------------------

function readJson(path: string): Json {
  return JSON.parse(readFileSync(path, "utf8")) as Json;
}

const writtenFiles: string[] = [];

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  writtenFiles.push(path);
}

function copyFixture(src: string, dest: string): void {
  writeFile(dest, readFileSync(src, "utf8"));
}

// ---------------------------------------------------------------------------
// 1. Events: validate fixtures, generate events package.
// ---------------------------------------------------------------------------

const EVENT_CONFIG: { file: string; goType: string; doc: string }[] = [
  {
    file: "deployment.export.requested.schema.json",
    goType: "ExportRequested",
    doc: "is the inbound event deployment.export.requested (PRD 0008 §8.1). Event fields renderMode/version/slug are hints reconciled against the authoritative deployment record (FR-004).",
  },
  {
    file: "deployment.artifact.ready.schema.json",
    goType: "ArtifactReady",
    doc: "is the outbound event deployment.artifact.ready (PRD 0010 §10.3.2; routes[] intentionally omitted per ADR-001). Emitted only after the CAS transition to ARTIFACT_READY succeeds (FR-013).",
  },
  {
    file: "deployment.export.failed.schema.json",
    goType: "ExportFailed",
    doc: "is the outbound event deployment.export.failed (PRD 0010 §10.3.2). Emitted with the final classified error code after the CAS transition to EXPORT_FAILED (FR-013, FR-014).",
  },
];

const EVENT_ENUM_TYPES: Record<string, string> = {
  renderMode: "RenderMode",
  environment: "Environment",
  errorClassification: "ErrorClassification",
  failedStage: "FailedStage",
  errorCode: "ErrorCode",
};

const EVENT_ENUM_DOCS: Record<string, string> = {
  RenderMode:
    "identifies the render strategy driver (PRD 0010 §6.3). fetch_route is the MVP mode; react_ssr and html_export are deferred.",
  Environment: "is the deployment environment (PRD 0010 §6.3).",
  ErrorClassification:
    "is the retry classification of an error code (PRD 0010 §13): RETRYABLE errors back off and retry up to maxRetries = 3, NON_RETRYABLE errors fail the deployment immediately.",
  FailedStage:
    "is the pipeline stage that failed — the trace-span vocabulary of PRD 0010 §15.3.",
  ErrorCode:
    "is a job-level error classification (full PRD 0010 §13 registry). New codes require a contracts version note.",
};

function generateEvents(): void {
  const enums = new Map<string, EnumSpec>();
  const structs: string[] = [];
  const schemaConsts: { constName: string; raw: string }[] = [];

  for (const cfg of EVENT_CONFIG) {
    const schemaPath = join(EVENTS_DIR, cfg.file);
    const raw = readFileSync(schemaPath, "utf8");
    const schema = readJson(schemaPath) as Schema;
    const props = (schema.properties ?? {}) as { [k: string]: Schema };

    for (const [prop, propSchema] of Object.entries(props)) {
      const goType = EVENT_ENUM_TYPES[prop];
      if (!goType || !Array.isArray(propSchema.enum)) continue;
      const values = propSchema.enum as string[];
      const existing = enums.get(goType);
      if (existing) {
        if (JSON.stringify(existing.values) !== JSON.stringify(values)) {
          throw new Error(`enum ${goType} differs between event schemas`);
        }
      } else {
        enums.set(goType, { goType, values, doc: EVENT_ENUM_DOCS[goType] });
      }
    }

    structs.push(
      emitStruct(cfg.goType, cfg.doc, schema, EVENT_ENUM_TYPES, () => {
        throw new Error("$ref not supported in event schemas");
      }),
    );
    if (raw.includes("`")) throw new Error(`${cfg.file} contains a backtick`);
    schemaConsts.push({ constName: `Schema${cfg.goType}`, raw });

    // Validate fixtures.
    const fixturePath = join(EVENTS_DIR, "fixtures", cfg.file.replace(".schema.json", ".json"));
    assertValid(schema, readJson(fixturePath), schema, relative(REPO_ROOT, fixturePath));
  }

  // Invalid fixtures must fail against their schema (longest-prefix filename match).
  const invalidDir = join(EVENTS_DIR, "fixtures", "invalid");
  for (const name of readdirSync(invalidDir).sort()) {
    const cfg = EVENT_CONFIG.filter((c) =>
      name.startsWith(c.file.replace(".schema.json", "")),
    ).sort((a, b) => b.file.length - a.file.length)[0];
    if (!cfg) throw new Error(`invalid fixture ${name} matches no event schema`);
    const schema = readJson(join(EVENTS_DIR, cfg.file)) as Schema;
    assertInvalid(schema, readJson(join(invalidDir, name)), schema, name);
  }

  const eventTypeConsts = EVENT_CONFIG.map((c) => {
    const schema = readJson(join(EVENTS_DIR, c.file)) as Schema;
    const props = schema.properties as { [k: string]: Schema };
    return { name: `EventType${c.goType}`, value: props.eventType.const as string };
  });

  let out = GENERATED_HEADER("contracts/events/v1");
  out += "\n";
  out +=
    "// Package events contains Go bindings for the versioned AnvilKit platform\n" +
    "// event contracts (contracts/events/v1). The JSON Schema files are the\n" +
    "// contract of record; this package is generated from them and committed so\n" +
    "// the worker repo builds standalone. Platform CI regenerates and fails on\n" +
    "// drift. Contracts evolve additively only (FR-002, ADR-001).\n";
  out += "package events\n\n";
  out += "// Event type discriminators.\nconst (\n";
  for (const c of eventTypeConsts) out += `\t${c.name} = "${c.value}"\n`;
  out += ")\n\n";
  for (const goType of ["RenderMode", "Environment", "ErrorClassification", "FailedStage", "ErrorCode"]) {
    const spec = enums.get(goType);
    if (spec) out += emitEnum(spec) + "\n";
  }
  out += structs.join("\n");
  writeFile(join(GO_CONTRACTS_DIR, "events", "events_gen.go"), out);

  let schemasOut = GENERATED_HEADER("contracts/events/v1");
  schemasOut += "\npackage events\n\n";
  schemasOut +=
    "// Raw JSON Schema sources (draft 2020-12), embedded so the worker can\n" +
    "// validate payloads offline without a filesystem dependency on the\n" +
    "// platform repo.\nconst (\n";
  for (const sc of schemaConsts) {
    schemasOut += `\t${sc.constName} = \`${sc.raw}\`\n\n`;
  }
  schemasOut += ")\n";
  writeFile(join(GO_CONTRACTS_DIR, "events", "schemas_gen.go"), schemasOut);

  for (const cfg of EVENT_CONFIG) {
    const fixture = cfg.file.replace(".schema.json", ".json");
    copyFixture(
      join(EVENTS_DIR, "fixtures", fixture),
      join(GO_CONTRACTS_DIR, "events", "testdata", fixture),
    );
  }
}

// ---------------------------------------------------------------------------
// 2. OpenAPI: validate fixtures, generate service packages (types + client).
// ---------------------------------------------------------------------------

interface ServiceConfig {
  file: string;
  goPackage: string;
  fixtures: Record<string, string>; // fixture file → component schema name
  invalidFixtures: Record<string, string>; // invalid fixture file → component schema it must fail
}

const SERVICE_CONFIG: ServiceConfig[] = [
  {
    file: "deployment-service.internal.json",
    goPackage: "deploymentservice",
    fixtures: {
      "deployment-record.json": "DeploymentRecord",
      "status-update.json": "StatusUpdateRequest",
      "status-conflict.json": "StatusConflictError",
      "artifact-pointer.json": "ArtifactPointer",
    },
    invalidFixtures: {
      "deployment-record.bad-render-mode.json": "DeploymentRecord",
      "status-update.missing-trace-id.json": "StatusUpdateRequest",
      "status-conflict.bad-error-const.json": "StatusConflictError",
      "artifact-pointer.bad-digest-prefix.json": "ArtifactPointer",
    },
  },
  {
    file: "asset-service.internal.json",
    goPackage: "assetservice",
    fixtures: {
      "resolve-batch-request.json": "ResolveBatchRequest",
      "resolve-batch-response.json": "ResolveBatchResponse",
    },
    invalidFixtures: {
      "resolve-batch-request.bad-ref-scheme.json": "ResolveBatchRequest",
      "resolve-batch-response.bad-content-hash.json": "ResolveBatchResponse",
    },
  },
];

interface Operation {
  method: string;
  path: string;
  op: Schema;
}

function collectOperations(doc: Schema): Operation[] {
  const ops: Operation[] = [];
  const paths = doc.paths as { [k: string]: Schema };
  for (const [path, item] of Object.entries(paths)) {
    for (const method of ["get", "post", "patch", "put", "delete"]) {
      if (item[method]) ops.push({ method, path, op: item[method] as Schema });
    }
  }
  return ops;
}

function errorResponseSchemas(doc: Schema): Set<string> {
  // Component schema names referenced from non-2xx response bodies.
  const names = new Set<string>();
  for (const { op } of collectOperations(doc)) {
    const responses = (op.responses ?? {}) as { [k: string]: Schema };
    for (const [status, resp] of Object.entries(responses)) {
      if (status.startsWith("2")) continue;
      const ref = (resp as any)?.content?.["application/json"]?.schema?.$ref;
      if (typeof ref === "string") names.add(ref.split("/").pop() as string);
    }
  }
  return names;
}

function generateService(cfg: ServiceConfig): void {
  const docPath = join(OPENAPI_DIR, cfg.file);
  const doc = readJson(docPath) as Schema;
  const schemas = ((doc.components as Schema).schemas ?? {}) as { [k: string]: Schema };
  const refNamer = (ref: string) => ref.split("/").pop() as string;
  const errorSchemas = errorResponseSchemas(doc);
  const sourceRel = `contracts/openapi/v1/${cfg.file}`;

  // Validate fixtures against component schemas.
  for (const [fixture, schemaName] of Object.entries(cfg.fixtures)) {
    const fixturePath = join(OPENAPI_DIR, "fixtures", fixture);
    assertValid(schemas[schemaName], readJson(fixturePath), doc, fixture);
    copyFixture(fixturePath, join(GO_CONTRACTS_DIR, cfg.goPackage, "testdata", fixture));
  }

  // Invalid fixtures must fail against their component schema (parity with the
  // events/artifact corpora). Validation-only: not copied into Go testdata.
  for (const [fixture, schemaName] of Object.entries(cfg.invalidFixtures)) {
    const fixturePath = join(OPENAPI_DIR, "fixtures", "invalid", fixture);
    assertInvalid(schemas[schemaName], readJson(fixturePath), doc, fixture);
  }

  // --- types_gen.go ---
  let types = GENERATED_HEADER(sourceRel);
  types += "\n";
  types += `// Package ${cfg.goPackage} contains Go bindings for the ${(doc.info as Schema).title}.\n`;
  types += `// The OpenAPI document is the contract of record; shapes preserve\n`;
  types += `// PRD 0008 §8 / PRD 0010 §8 exactly. Generated and committed; platform CI\n`;
  types += `// regenerates and fails on drift (FR-002).\n`;
  types += `package ${cfg.goPackage}\n\n`;
  types += `import "fmt"\n\n`;
  const structs: string[] = [];
  const enumsOut: string[] = [];
  for (const [name, schema] of Object.entries(schemas)) {
    if (schema.type === "string" && Array.isArray(schema.enum)) {
      enumsOut.push(
        emitEnum({
          goType: name,
          values: schema.enum as string[],
          doc: typeof schema.description === "string" ? schema.description : "",
        }),
      );
      continue;
    }
    const doc_ = typeof schema.description === "string" ? schema.description : "";
    // Error-response schemas grow an Error() method — rename a property that
    // would collide with it (e.g. StatusConflictError.error → ErrorCode).
    const renames: Record<string, string> = errorSchemas.has(name) ? { error: "ErrorCode" } : {};
    structs.push(emitStruct(name, doc_, schema, {}, refNamer, renames));
  }
  types += enumsOut.concat(structs).join("\n");
  // Error() methods for schemas used as error response bodies.
  for (const name of [...errorSchemas].sort()) {
    types += `\n// Error implements the error interface: a decoded ${name} response is\n`;
    types += `// returned directly as a typed error by the generated client.\n`;
    types += `func (e *${name}) Error() string {\n`;
    types += `\treturn fmt.Sprintf("${cfg.goPackage}: %+v", *e)\n`;
    types += `}\n`;
  }
  if (!types.includes("fmt.Sprintf")) {
    types = types.replace(`import "fmt"\n\n`, "");
  }
  writeFile(join(GO_CONTRACTS_DIR, cfg.goPackage, "types_gen.go"), types);

  // --- client_gen.go ---
  const hasPathParams = collectOperations(doc).some(({ op }) =>
    ((op.parameters ?? []) as Schema[]).some((p) => {
      const resolved = typeof p.$ref === "string" ? resolveRef(doc, p.$ref) : p;
      return resolved.in === "path";
    }),
  );
  let cl = GENERATED_HEADER(sourceRel);
  cl += `\npackage ${cfg.goPackage}\n\n`;
  const imports = ["bytes", "context", "encoding/json", "fmt", "io", "net/http"];
  if (hasPathParams) imports.push("net/url");
  imports.push("strings");
  cl += `import (\n${imports.map((i) => `\t"${i}"`).join("\n")}\n)\n\n`;
  cl += `// Client is a minimal generated client for the ${(doc.info as Schema).title}.\n`;
  cl += `// It owns transport mechanics only. Worker-level concerns — retryable-error\n`;
  cl += `// mapping, timeout budgets, alerting classification — belong to the client\n`;
  cl += `// wrapper tasks (EW-DEPLOY-001 / EW-ARTIFACT-*), not to generated code.\n`;
  cl += `type Client struct {\n`;
  cl += `\t// BaseURL is the service base URL, e.g. ${((doc.servers as Json[])[0] as Schema).url}.\n`;
  cl += `\tBaseURL string\n`;
  cl += `\t// Token is the INTERNAL_SERVICE_TOKEN bearer credential (PRD 0010 §11.1).\n`;
  cl += `\tToken string\n`;
  cl += `\t// HTTPClient is the underlying transport; http.DefaultClient when nil.\n`;
  cl += `\tHTTPClient *http.Client\n`;
  cl += `}\n\n`;
  cl += `// APIError is returned for responses with no operation-specific mapping.\n`;
  cl += `type APIError struct {\n\tStatusCode int\n\tBody       []byte\n}\n\n`;
  cl += `func (e *APIError) Error() string {\n`;
  cl += `\tbody := e.Body\n\tif len(body) > 512 {\n\t\tbody = body[:512]\n\t}\n`;
  cl += `\treturn fmt.Sprintf("${cfg.goPackage}: unexpected status %d: %s", e.StatusCode, string(body))\n}\n\n`;

  for (const { method, path, op } of collectOperations(doc)) {
    const operationId = op.operationId as string;
    const goMethod = operationId.charAt(0).toUpperCase() + operationId.slice(1);
    const params = ((op.parameters ?? []) as Schema[]).map((p) =>
      typeof p.$ref === "string" ? resolveRef(doc, p.$ref) : p,
    );
    const pathParams = params.filter((p) => p.in === "path").map((p) => p.name as string);
    const bodyRef = (op as any)?.requestBody?.content?.["application/json"]?.schema?.$ref;
    const bodyType = typeof bodyRef === "string" ? refNamer(bodyRef) : null;
    const responses = (op.responses ?? {}) as { [k: string]: Schema };
    let successType: string | null = null;
    for (const [status, resp] of Object.entries(responses)) {
      if (!status.startsWith("2")) continue;
      const ref = (resp as any)?.content?.["application/json"]?.schema?.$ref;
      if (typeof ref === "string") successType = refNamer(ref);
    }
    const errorHooks: { status: string; type: string }[] = [];
    for (const [status, resp] of Object.entries(responses)) {
      if (status.startsWith("2")) continue;
      const ref = (resp as any)?.content?.["application/json"]?.schema?.$ref;
      if (typeof ref === "string") errorHooks.push({ status, type: refNamer(ref) });
    }

    // Build Go path expression from the template.
    const segments = path.split("/").filter(Boolean);
    const exprParts: string[] = [];
    let literal = "";
    for (const seg of segments) {
      const m = seg.match(/^\{(.+)\}$/);
      if (m) {
        if (literal) {
          exprParts.push(`"${literal}/"`);
          literal = "";
        } else {
          exprParts.push(`"/"`);
        }
        exprParts.push(`url.PathEscape(${goArgName(m[1])})`);
      } else {
        literal += "/" + seg;
      }
    }
    if (literal) exprParts.push(`"${literal}"`);
    // Normalize: first literal must start with "/".
    if (exprParts.length > 0 && exprParts[0].startsWith(`"`) && !exprParts[0].startsWith(`"/`)) {
      exprParts[0] = `"/` + exprParts[0].slice(1);
    }
    const pathExpr = exprParts.join(" + ");

    const args: string[] = ["ctx context.Context"];
    for (const p of pathParams) args.push(`${goArgName(p)} string`);
    if (bodyType) args.push(`body ${bodyType}`);

    const summary = typeof op.summary === "string" ? op.summary : operationId;
    cl += `// ${goMethod} — ${summary}.\n`;
    cl += `// ${method.toUpperCase()} ${path}\n`;
    if (successType) {
      cl += `func (c *Client) ${goMethod}(${args.join(", ")}) (*${successType}, error) {\n`;
    } else {
      cl += `func (c *Client) ${goMethod}(${args.join(", ")}) error {\n`;
    }
    cl += `\tpath := ${pathExpr}\n`;
    let hooksExpr = "nil";
    if (errorHooks.length > 0) {
      hooksExpr = "map[int]func([]byte) error{\n";
      for (const h of errorHooks) {
        hooksExpr += `\t\t${h.status}: func(b []byte) error {\n`;
        hooksExpr += `\t\t\tvar e ${h.type}\n`;
        hooksExpr += `\t\t\tif err := json.Unmarshal(b, &e); err != nil {\n`;
        hooksExpr += `\t\t\t\treturn &APIError{StatusCode: ${h.status}, Body: b}\n\t\t\t}\n`;
        hooksExpr += `\t\t\treturn &e\n\t\t},\n`;
      }
      hooksExpr += "\t}";
    }
    const inExpr = bodyType ? "&body" : "nil";
    if (successType) {
      cl += `\tvar out ${successType}\n`;
      cl += `\tif err := c.do(ctx, "${method.toUpperCase()}", path, ${inExpr}, &out, ${hooksExpr}); err != nil {\n`;
      cl += `\t\treturn nil, err\n\t}\n`;
      cl += `\treturn &out, nil\n`;
    } else {
      cl += `\treturn c.do(ctx, "${method.toUpperCase()}", path, ${inExpr}, nil, ${hooksExpr})\n`;
    }
    cl += `}\n\n`;
  }

  cl += `func (c *Client) do(ctx context.Context, method, path string, in, out any, errHooks map[int]func([]byte) error) error {\n`;
  cl += `\tvar reqBody io.Reader\n`;
  cl += `\tif in != nil {\n\t\tbuf, err := json.Marshal(in)\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\t\treqBody = bytes.NewReader(buf)\n\t}\n`;
  cl += `\treq, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.BaseURL, "/")+path, reqBody)\n`;
  cl += `\tif err != nil {\n\t\treturn err\n\t}\n`;
  cl += `\tif in != nil {\n\t\treq.Header.Set("Content-Type", "application/json")\n\t}\n`;
  cl += `\tif c.Token != "" {\n\t\treq.Header.Set("Authorization", "Bearer "+c.Token)\n\t}\n`;
  cl += `\thc := c.HTTPClient\n\tif hc == nil {\n\t\thc = http.DefaultClient\n\t}\n`;
  cl += `\tresp, err := hc.Do(req)\n\tif err != nil {\n\t\treturn err\n\t}\n`;
  cl += `\tdefer resp.Body.Close()\n`;
  cl += `\tbody, err := io.ReadAll(resp.Body)\n\tif err != nil {\n\t\treturn err\n\t}\n`;
  cl += `\tif resp.StatusCode >= 200 && resp.StatusCode < 300 {\n`;
  cl += `\t\tif out != nil && len(body) > 0 {\n\t\t\treturn json.Unmarshal(body, out)\n\t\t}\n\t\treturn nil\n\t}\n`;
  cl += `\tif hook, ok := errHooks[resp.StatusCode]; ok {\n\t\treturn hook(body)\n\t}\n`;
  cl += `\treturn &APIError{StatusCode: resp.StatusCode, Body: body}\n}\n`;
  writeFile(join(GO_CONTRACTS_DIR, cfg.goPackage, "client_gen.go"), cl);
}

// ---------------------------------------------------------------------------
// 3. Artifact manifest: validate fixtures, generate artifact package.
// ---------------------------------------------------------------------------

function generateArtifact(): void {
  const schemaPath = join(ARTIFACT_DIR, "artifact-manifest.schema.json");
  const raw = readFileSync(schemaPath, "utf8");
  if (raw.includes("`")) throw new Error("artifact-manifest.schema.json contains a backtick");
  const schema = readJson(schemaPath) as Schema;
  const props = (schema.properties ?? {}) as { [k: string]: Schema };
  const noRefs = () => {
    throw new Error("$ref not supported in the artifact schema");
  };

  // Validate fixtures.
  const fixturePath = join(ARTIFACT_DIR, "fixtures", "artifact-manifest.json");
  assertValid(schema, readJson(fixturePath), schema, "artifact-manifest.json");
  const invalidDir = join(ARTIFACT_DIR, "fixtures", "invalid");
  for (const name of readdirSync(invalidDir).sort()) {
    assertInvalid(schema, readJson(join(invalidDir, name)), schema, name);
  }

  let out = GENERATED_HEADER("contracts/artifact/v1");
  out += "\n";
  out +=
    "// Package artifact contains Go bindings for artifact-manifest.json —\n" +
    "// the canonical description of one deployment's static artifact bundle\n" +
    "// (PRD 0008 §9.2; FR-012). The manifest is internal-only (private,\n" +
    "// max-age=0, no-store) and routes[] is always an array. The JSON Schema\n" +
    "// file is the contract of record; this package is generated from it.\n";
  out += "package artifact\n\n";
  out += emitStruct(
    "ManifestFile",
    "is one object in the artifact bundle. contentHash matches the object's x-amz-meta-content-sha256 metadata — never an S3 ETag (FR-011).",
    props.files.items as Schema,
    {},
    noRefs,
  );
  out += "\n";
  out += emitStruct(
    "ManifestRoute",
    "is one route mapping within the artifact.",
    props.routes.items as Schema,
    {},
    noRefs,
  );
  out += "\n";
  out += emitStruct(
    "Manifest",
    "is artifact-manifest.json (schemaVersion 1).",
    schema,
    {},
    noRefs,
    {},
    { files: "[]ManifestFile", routes: "[]ManifestRoute" },
  );
  writeFile(join(GO_CONTRACTS_DIR, "artifact", "manifest_gen.go"), out);

  let schemaOut = GENERATED_HEADER("contracts/artifact/v1");
  schemaOut += "\npackage artifact\n\n";
  schemaOut +=
    "// SchemaArtifactManifest is the raw JSON Schema source (draft 2020-12),\n" +
    "// embedded so the manifest builder can validate its own output offline\n" +
    "// (EW-STORAGE-005 DoD).\n";
  schemaOut += `const SchemaArtifactManifest = \`${raw}\`\n`;
  writeFile(join(GO_CONTRACTS_DIR, "artifact", "schemas_gen.go"), schemaOut);

  copyFixture(fixturePath, join(GO_CONTRACTS_DIR, "artifact", "testdata", "artifact-manifest.json"));
}

// ---------------------------------------------------------------------------
// 4. Freeze lock.
// ---------------------------------------------------------------------------

function walkContracts(dir: string, acc: string[]): void {
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      walkContracts(full, acc);
    } else {
      acc.push(full);
    }
  }
}

function computeLock(): { [k: string]: string } {
  const files: string[] = [];
  walkContracts(CONTRACTS_DIR, files);
  const lock: { [k: string]: string } = {};
  for (const f of files) {
    const rel = relative(REPO_ROOT, f);
    if (rel === "contracts/contracts.lock.json" || rel === "contracts/README.md") continue;
    lock[rel] = createHash("sha256").update(readFileSync(f)).digest("hex");
  }
  return lock;
}

// ---------------------------------------------------------------------------
// Main.
// ---------------------------------------------------------------------------

generateEvents();
for (const cfg of SERVICE_CONFIG) generateService(cfg);
generateArtifact();

const goFiles = writtenFiles.filter((f) => f.endsWith(".go"));
const gofmt = spawnSync("gofmt", ["-w", ...goFiles], { stdio: "inherit" });
if (gofmt.error || gofmt.status !== 0) {
  throw new Error("gofmt failed — is the Go toolchain installed?");
}

if (process.argv.includes("--update-lock")) {
  const lock = {
    _comment:
      "Freeze lock for versioned contracts (ADR-001, AC-029). Frozen files are immutable: contracts evolve additively via generate.ts --update-lock (visible in review) or a new version directory. CI verifies via packages/contracts-codegen/check-freeze.ts.",
    lockVersion: 1,
    files: computeLock(),
  };
  writeFileSync(LOCK_PATH, JSON.stringify(lock, null, 2) + "\n");
  console.log(`wrote ${relative(REPO_ROOT, LOCK_PATH)}`);
}

console.log(`validated fixtures and generated ${goFiles.length} Go files + testdata:`);
for (const f of writtenFiles) console.log(`  ${relative(REPO_ROOT, f)}`);
