# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.shared_primitives_v1_artifact_reference import SharedPrimitivesV1ArtifactReference
from anvilkit_pagix_client.models.shared_primitives_v1_contract_bom_reference_v1 import SharedPrimitivesV1ContractBomReferenceV1
from anvilkit_pagix_client.models.shared_primitives_v1_trace_context import SharedPrimitivesV1TraceContext
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentEventV1(BaseModel):
    """
    Bounded AgentEventV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    artifact_reference: Optional[SharedPrimitivesV1ArtifactReference] = Field(default=None, alias="artifactReference")
    contract_bom_reference: SharedPrimitivesV1ContractBomReferenceV1 = Field(alias="contractBomReference")
    event_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="eventId")
    event_type: StrictStr = Field(alias="eventType")
    kind: Optional[Any]
    occurred_at: datetime = Field(alias="occurredAt")
    payload: Optional[Dict[str, Annotated[str, Field(min_length=0, strict=True, max_length=1024)]]] = None
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="runId")
    sequence: Annotated[int, Field(le=9007199254740991, strict=True, ge=1)]
    task_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = Field(default=None, alias="taskId")
    trace_context: SharedPrimitivesV1TraceContext = Field(alias="traceContext")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "artifactReference", "contractBomReference", "eventId", "eventType", "kind", "occurredAt", "payload", "runId", "sequence", "taskId", "traceContext"]

    @field_validator('event_id')
    def event_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['run.created', 'run.state-changed', 'run.input-requested', 'run.approval-requested', 'run.artifact-available', 'run.problem-recorded']):
            raise ValueError("must be one of enum values ('run.created', 'run.state-changed', 'run.input-requested', 'run.approval-requested', 'run.artifact-available', 'run.problem-recorded')")
        return value

    @field_validator('occurred_at')
    def occurred_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('task_id')
    def task_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentEventV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of artifact_reference
        if self.artifact_reference:
            _dict['artifactReference'] = self.artifact_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contract_bom_reference
        if self.contract_bom_reference:
            _dict['contractBomReference'] = self.contract_bom_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trace_context
        if self.trace_context:
            _dict['traceContext'] = self.trace_context.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentEventV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "artifactReference": SharedPrimitivesV1ArtifactReference.from_dict(obj["artifactReference"]) if obj.get("artifactReference") is not None else None,
            "contractBomReference": SharedPrimitivesV1ContractBomReferenceV1.from_dict(obj["contractBomReference"]) if obj.get("contractBomReference") is not None else None,
            "eventId": obj.get("eventId"),
            "eventType": obj.get("eventType"),
            "kind": obj.get("kind"),
            "occurredAt": obj.get("occurredAt"),
            "payload": obj.get("payload"),
            "runId": obj.get("runId"),
            "sequence": obj.get("sequence"),
            "taskId": obj.get("taskId"),
            "traceContext": SharedPrimitivesV1TraceContext.from_dict(obj["traceContext"]) if obj.get("traceContext") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


