# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentArtifactV1Producer(BaseModel):
    """
    AgentArtifactV1Producer
    """ # noqa: E501
    execution_generation: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="executionGeneration")
    lease_epoch: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="leaseEpoch")
    physical_attempt_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="physicalAttemptId")
    recovery_epoch: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="recoveryEpoch")
    task_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="taskId")
    __properties: ClassVar[List[str]] = ["executionGeneration", "leaseEpoch", "physicalAttemptId", "recoveryEpoch", "taskId"]

    @field_validator('physical_attempt_id')
    def physical_attempt_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('task_id')
    def task_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentArtifactV1Producer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentArtifactV1Producer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "executionGeneration": obj.get("executionGeneration"),
            "leaseEpoch": obj.get("leaseEpoch"),
            "physicalAttemptId": obj.get("physicalAttemptId"),
            "recoveryEpoch": obj.get("recoveryEpoch"),
            "taskId": obj.get("taskId")
        })
        return _obj


