# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.agent_budget_v1_currency_limits import AgentBudgetV1CurrencyLimits
from anvilkit_pagix_client.models.agent_budget_v1_gpu_limits import AgentBudgetV1GpuLimits
from anvilkit_pagix_client.models.agent_budget_v1_model_limits import AgentBudgetV1ModelLimits
from anvilkit_pagix_client.models.agent_budget_v1_token_limits import AgentBudgetV1TokenLimits
from anvilkit_pagix_client.models.agent_budget_v1_worker_limits import AgentBudgetV1WorkerLimits
from anvilkit_pagix_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentBudgetV1(BaseModel):
    """
    Bounded AgentBudgetV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    currency_limits: AgentBudgetV1CurrencyLimits = Field(alias="currencyLimits")
    exceed_behavior: StrictStr = Field(alias="exceedBehavior")
    gpu_limits: AgentBudgetV1GpuLimits = Field(alias="gpuLimits")
    kind: Optional[Any]
    model_limits: AgentBudgetV1ModelLimits = Field(alias="modelLimits")
    policy: SharedPrimitivesV1PolicyReference
    reservation_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="reservationId")
    token_limits: AgentBudgetV1TokenLimits = Field(alias="tokenLimits")
    worker_limits: AgentBudgetV1WorkerLimits = Field(alias="workerLimits")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "currencyLimits", "exceedBehavior", "gpuLimits", "kind", "modelLimits", "policy", "reservationId", "tokenLimits", "workerLimits"]

    @field_validator('exceed_behavior')
    def exceed_behavior_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['refuse', 'pause-for-approval', 'cancel']):
            raise ValueError("must be one of enum values ('refuse', 'pause-for-approval', 'cancel')")
        return value

    @field_validator('reservation_id')
    def reservation_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentBudgetV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency_limits
        if self.currency_limits:
            _dict['currencyLimits'] = self.currency_limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gpu_limits
        if self.gpu_limits:
            _dict['gpuLimits'] = self.gpu_limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of model_limits
        if self.model_limits:
            _dict['modelLimits'] = self.model_limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of token_limits
        if self.token_limits:
            _dict['tokenLimits'] = self.token_limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of worker_limits
        if self.worker_limits:
            _dict['workerLimits'] = self.worker_limits.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentBudgetV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "currencyLimits": AgentBudgetV1CurrencyLimits.from_dict(obj["currencyLimits"]) if obj.get("currencyLimits") is not None else None,
            "exceedBehavior": obj.get("exceedBehavior"),
            "gpuLimits": AgentBudgetV1GpuLimits.from_dict(obj["gpuLimits"]) if obj.get("gpuLimits") is not None else None,
            "kind": obj.get("kind"),
            "modelLimits": AgentBudgetV1ModelLimits.from_dict(obj["modelLimits"]) if obj.get("modelLimits") is not None else None,
            "policy": SharedPrimitivesV1PolicyReference.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "reservationId": obj.get("reservationId"),
            "tokenLimits": AgentBudgetV1TokenLimits.from_dict(obj["tokenLimits"]) if obj.get("tokenLimits") is not None else None,
            "workerLimits": AgentBudgetV1WorkerLimits.from_dict(obj["workerLimits"]) if obj.get("workerLimits") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


