# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.agent_artifact_v1_producer import AgentArtifactV1Producer
from anvilkit_pagix_client.models.agent_artifact_v1_reference import AgentArtifactV1Reference
from anvilkit_pagix_client.models.agent_artifact_v1_validation import AgentArtifactV1Validation
from anvilkit_pagix_client.models.shared_primitives_v1_artifact_reference import SharedPrimitivesV1ArtifactReference
from anvilkit_pagix_client.models.shared_primitives_v1_schema_reference import SharedPrimitivesV1SchemaReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentArtifactV1(BaseModel):
    """
    Bounded AgentArtifactV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    artifact_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="artifactId")
    contract_type: Optional[Any] = Field(alias="contractType")
    created_at: datetime = Field(alias="createdAt")
    digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)]
    kind: StrictStr
    lifecycle: StrictStr
    lineage: Annotated[List[SharedPrimitivesV1ArtifactReference], Field(min_length=0, max_length=64)]
    producer: AgentArtifactV1Producer
    reference: AgentArtifactV1Reference
    var_schema: SharedPrimitivesV1SchemaReference = Field(alias="schema")
    validation: AgentArtifactV1Validation
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "artifactId", "contractType", "createdAt", "digest", "kind", "lifecycle", "lineage", "producer", "reference", "schema", "validation"]

    @field_validator('artifact_id')
    def artifact_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('created_at')
    def created_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('digest')
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['compiled-context', 'target-snapshot', 'agent-plan', 'worker-result', 'validation-report']):
            raise ValueError("must be one of enum values ('compiled-context', 'target-snapshot', 'agent-plan', 'worker-result', 'validation-report')")
        return value

    @field_validator('lifecycle')
    def lifecycle_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'scanning', 'valid', 'finalized', 'committed', 'quarantined', 'expired', 'deleted']):
            raise ValueError("must be one of enum values ('pending', 'scanning', 'valid', 'finalized', 'committed', 'quarantined', 'expired', 'deleted')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentArtifactV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lineage (list)
        _items = []
        if self.lineage:
            for _item_lineage in self.lineage:
                if _item_lineage:
                    _items.append(_item_lineage.to_dict())
            _dict['lineage'] = _items
        # override the default output from pydantic by calling `to_dict()` of producer
        if self.producer:
            _dict['producer'] = self.producer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reference
        if self.reference:
            _dict['reference'] = self.reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict['validation'] = self.validation.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if contract_type (nullable) is None
        # and model_fields_set contains the field
        if self.contract_type is None and "contract_type" in self.model_fields_set:
            _dict['contractType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentArtifactV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "artifactId": obj.get("artifactId"),
            "contractType": obj.get("contractType"),
            "createdAt": obj.get("createdAt"),
            "digest": obj.get("digest"),
            "kind": obj.get("kind"),
            "lifecycle": obj.get("lifecycle"),
            "lineage": [SharedPrimitivesV1ArtifactReference.from_dict(_item) for _item in obj["lineage"]] if obj.get("lineage") is not None else None,
            "producer": AgentArtifactV1Producer.from_dict(obj["producer"]) if obj.get("producer") is not None else None,
            "reference": AgentArtifactV1Reference.from_dict(obj["reference"]) if obj.get("reference") is not None else None,
            "schema": SharedPrimitivesV1SchemaReference.from_dict(obj["schema"]) if obj.get("schema") is not None else None,
            "validation": AgentArtifactV1Validation.from_dict(obj["validation"]) if obj.get("validation") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


