# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.approval_request_v1_effects_inner import ApprovalRequestV1EffectsInner
from anvilkit_pagix_client.models.shared_primitives_v1_cost import SharedPrimitivesV1Cost
from anvilkit_pagix_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApprovalRequestV1(BaseModel):
    """
    Bounded ApprovalRequestV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    action_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="actionDigest")
    allowed_decisions: Annotated[List[StrictStr], Field(min_length=1, max_length=3)] = Field(alias="allowedDecisions")
    api_version: Optional[Any] = Field(alias="apiVersion")
    cost: SharedPrimitivesV1Cost
    decision_version: Annotated[int, Field(le=9007199254740991, strict=True, ge=1)] = Field(alias="decisionVersion")
    effects: Annotated[List[ApprovalRequestV1EffectsInner], Field(min_length=1, max_length=32)]
    expires_at: datetime = Field(alias="expiresAt")
    kind: Optional[Any]
    request_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="requestId")
    resume_state: StrictStr = Field(alias="resumeState")
    reviewer_policy: SharedPrimitivesV1PolicyReference = Field(alias="reviewerPolicy")
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="runId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["actionDigest", "allowedDecisions", "apiVersion", "cost", "decisionVersion", "effects", "expiresAt", "kind", "requestId", "resumeState", "reviewerPolicy", "runId"]

    @field_validator('action_digest')
    def action_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('allowed_decisions')
    def allowed_decisions_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['approve', 'reject', 'request-changes']):
                raise ValueError("each list item must be one of ('approve', 'reject', 'request-changes')")
        return value

    @field_validator('expires_at')
    def expires_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('request_id')
    def request_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('resume_state')
    def resume_state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['created', 'preparing', 'planning', 'awaiting_input', 'executing', 'validating', 'awaiting_review', 'awaiting_approval', 'committing', 'awaiting_domain_confirmation', 'conflict', 'cancelling', 'failed', 'completed', 'cancelled', 'refused', 'discarded']):
            raise ValueError("must be one of enum values ('created', 'preparing', 'planning', 'awaiting_input', 'executing', 'validating', 'awaiting_review', 'awaiting_approval', 'committing', 'awaiting_domain_confirmation', 'conflict', 'cancelling', 'failed', 'completed', 'cancelled', 'refused', 'discarded')")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApprovalRequestV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in effects (list)
        _items = []
        if self.effects:
            for _item_effects in self.effects:
                if _item_effects:
                    _items.append(_item_effects.to_dict())
            _dict['effects'] = _items
        # override the default output from pydantic by calling `to_dict()` of reviewer_policy
        if self.reviewer_policy:
            _dict['reviewerPolicy'] = self.reviewer_policy.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApprovalRequestV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actionDigest": obj.get("actionDigest"),
            "allowedDecisions": obj.get("allowedDecisions"),
            "apiVersion": obj.get("apiVersion"),
            "cost": SharedPrimitivesV1Cost.from_dict(obj["cost"]) if obj.get("cost") is not None else None,
            "decisionVersion": obj.get("decisionVersion"),
            "effects": [ApprovalRequestV1EffectsInner.from_dict(_item) for _item in obj["effects"]] if obj.get("effects") is not None else None,
            "expiresAt": obj.get("expiresAt"),
            "kind": obj.get("kind"),
            "requestId": obj.get("requestId"),
            "resumeState": obj.get("resumeState"),
            "reviewerPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["reviewerPolicy"]) if obj.get("reviewerPolicy") is not None else None,
            "runId": obj.get("runId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


