# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompiledContextV1OrderedTrustLayersInner(BaseModel):
    """
    CompiledContextV1OrderedTrustLayersInner
    """ # noqa: E501
    classification: StrictStr
    digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)]
    layer_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="layerId")
    position: Annotated[int, Field(le=1023, strict=True, ge=0)]
    redacted: StrictBool
    token_budget: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="tokenBudget")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["classification", "digest", "layerId", "position", "redacted", "tokenBudget"]

    @field_validator('classification')
    def classification_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['public', 'internal', 'confidential', 'restricted']):
            raise ValueError("must be one of enum values ('public', 'internal', 'confidential', 'restricted')")
        return value

    @field_validator('digest')
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('layer_id')
    def layer_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompiledContextV1OrderedTrustLayersInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompiledContextV1OrderedTrustLayersInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "classification": obj.get("classification"),
            "digest": obj.get("digest"),
            "layerId": obj.get("layerId"),
            "position": obj.get("position"),
            "redacted": obj.get("redacted"),
            "tokenBudget": obj.get("tokenBudget")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


