# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.component_package_spec_v1_outputs_inner import ComponentPackageSpecV1OutputsInner
from anvilkit_pagix_client.models.component_package_spec_v1_package_intent import ComponentPackageSpecV1PackageIntent
from anvilkit_pagix_client.models.shared_primitives_v1_artifact_reference import SharedPrimitivesV1ArtifactReference
from anvilkit_pagix_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComponentPackageSpecV1(BaseModel):
    """
    Bounded ComponentPackageSpecV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    build_policy: SharedPrimitivesV1PolicyReference = Field(alias="buildPolicy")
    certification_policy: SharedPrimitivesV1PolicyReference = Field(alias="certificationPolicy")
    inputs: Annotated[List[SharedPrimitivesV1ArtifactReference], Field(min_length=0, max_length=64)]
    kind: Optional[Any]
    outputs: Annotated[List[ComponentPackageSpecV1OutputsInner], Field(min_length=1, max_length=64)]
    package_intent: ComponentPackageSpecV1PackageIntent = Field(alias="packageIntent")
    validation_constraints: Annotated[List[SharedPrimitivesV1PolicyReference], Field(min_length=1, max_length=32)] = Field(alias="validationConstraints")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "buildPolicy", "certificationPolicy", "inputs", "kind", "outputs", "packageIntent", "validationConstraints"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComponentPackageSpecV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of build_policy
        if self.build_policy:
            _dict['buildPolicy'] = self.build_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of certification_policy
        if self.certification_policy:
            _dict['certificationPolicy'] = self.certification_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in inputs (list)
        _items = []
        if self.inputs:
            for _item_inputs in self.inputs:
                if _item_inputs:
                    _items.append(_item_inputs.to_dict())
            _dict['inputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                if _item_outputs:
                    _items.append(_item_outputs.to_dict())
            _dict['outputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of package_intent
        if self.package_intent:
            _dict['packageIntent'] = self.package_intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in validation_constraints (list)
        _items = []
        if self.validation_constraints:
            for _item_validation_constraints in self.validation_constraints:
                if _item_validation_constraints:
                    _items.append(_item_validation_constraints.to_dict())
            _dict['validationConstraints'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComponentPackageSpecV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "buildPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["buildPolicy"]) if obj.get("buildPolicy") is not None else None,
            "certificationPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["certificationPolicy"]) if obj.get("certificationPolicy") is not None else None,
            "inputs": [SharedPrimitivesV1ArtifactReference.from_dict(_item) for _item in obj["inputs"]] if obj.get("inputs") is not None else None,
            "kind": obj.get("kind"),
            "outputs": [ComponentPackageSpecV1OutputsInner.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "packageIntent": ComponentPackageSpecV1PackageIntent.from_dict(obj["packageIntent"]) if obj.get("packageIntent") is not None else None,
            "validationConstraints": [SharedPrimitivesV1PolicyReference.from_dict(_item) for _item in obj["validationConstraints"]] if obj.get("validationConstraints") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


