# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from anvilkit_pagix_client.models.contract_trust_root_v1_keys_inner_public_key_jwk import ContractTrustRootV1KeysInnerPublicKeyJwk
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ContractTrustRootV1KeysInner(BaseModel):
    """
    ContractTrustRootV1KeysInner
    """ # noqa: E501
    algorithms: Annotated[List[StrictStr], Field(min_length=1, max_length=2)]
    audiences: Annotated[List[Annotated[str, Field(min_length=16, strict=True, max_length=256)]], Field(min_length=1, max_length=8)]
    issuer: Annotated[str, Field(min_length=16, strict=True, max_length=256)]
    key_id: Annotated[str, Field(min_length=16, strict=True, max_length=256)] = Field(alias="keyId")
    not_after: datetime = Field(alias="notAfter")
    not_before: datetime = Field(alias="notBefore")
    public_key_jwk: ContractTrustRootV1KeysInnerPublicKeyJwk = Field(alias="publicKeyJwk")
    status: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["algorithms", "audiences", "issuer", "keyId", "notAfter", "notBefore", "publicKeyJwk", "status"]

    @field_validator('algorithms')
    def algorithms_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['dsse-ed25519-v1', 'jws-eddsa-v1']):
                raise ValueError("each list item must be one of ('dsse-ed25519-v1', 'jws-eddsa-v1')")
        return value

    @field_validator('issuer')
    def issuer_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^urn:anvilkit:issuer:[a-z0-9][a-z0-9:-]*$", value):
            raise ValueError(r"must validate the regular expression /^urn:anvilkit:issuer:[a-z0-9][a-z0-9:-]*$/")
        return value

    @field_validator('key_id')
    def key_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^urn:anvilkit:key:[a-z0-9][a-z0-9:-]*$", value):
            raise ValueError(r"must validate the regular expression /^urn:anvilkit:key:[a-z0-9][a-z0-9:-]*$/")
        return value

    @field_validator('not_after')
    def not_after_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('not_before')
    def not_before_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'overlap', 'retired', 'revoked']):
            raise ValueError("must be one of enum values ('active', 'overlap', 'retired', 'revoked')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractTrustRootV1KeysInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of public_key_jwk
        if self.public_key_jwk:
            _dict['publicKeyJwk'] = self.public_key_jwk.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractTrustRootV1KeysInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "algorithms": obj.get("algorithms"),
            "audiences": obj.get("audiences"),
            "issuer": obj.get("issuer"),
            "keyId": obj.get("keyId"),
            "notAfter": obj.get("notAfter"),
            "notBefore": obj.get("notBefore"),
            "publicKeyJwk": ContractTrustRootV1KeysInnerPublicKeyJwk.from_dict(obj["publicKeyJwk"]) if obj.get("publicKeyJwk") is not None else None,
            "status": obj.get("status")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


