# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.problem_details_v1_field_errors_inner import ProblemDetailsV1FieldErrorsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProblemDetailsV1(BaseModel):
    """
    Bounded ProblemDetailsV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    code: Annotated[str, Field(min_length=3, strict=True, max_length=96)]
    field_errors: Annotated[List[ProblemDetailsV1FieldErrorsInner], Field(min_length=0, max_length=64)] = Field(alias="fieldErrors")
    kind: Optional[Any]
    message: Annotated[str, Field(min_length=1, strict=True, max_length=2048)]
    retryability: StrictStr
    run_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = Field(default=None, alias="runId")
    stage: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    trace_id: Optional[Annotated[str, Field(min_length=32, strict=True, max_length=32)]] = Field(default=None, alias="traceId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "code", "fieldErrors", "kind", "message", "retryability", "runId", "stage", "traceId"]

    @field_validator('code')
    def code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Z][A-Z0-9_.-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z][A-Z0-9_.-]+$/")
        return value

    @field_validator('retryability')
    def retryability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['never', 'safe-immediate', 'safe-after-backoff', 'after-input', 'after-approval', 'after-rebase', 'operator-action']):
            raise ValueError("must be one of enum values ('never', 'safe-immediate', 'safe-after-backoff', 'after-input', 'after-approval', 'after-rebase', 'operator-action')")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('stage')
    def stage_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z][a-z0-9._-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9._-]*$/")
        return value

    @field_validator('trace_id')
    def trace_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9a-f]{32}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{32}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProblemDetailsV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in field_errors (list)
        _items = []
        if self.field_errors:
            for _item_field_errors in self.field_errors:
                if _item_field_errors:
                    _items.append(_item_field_errors.to_dict())
            _dict['fieldErrors'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProblemDetailsV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "code": obj.get("code"),
            "fieldErrors": [ProblemDetailsV1FieldErrorsInner.from_dict(_item) for _item in obj["fieldErrors"]] if obj.get("fieldErrors") is not None else None,
            "kind": obj.get("kind"),
            "message": obj.get("message"),
            "retryability": obj.get("retryability"),
            "runId": obj.get("runId"),
            "stage": obj.get("stage"),
            "traceId": obj.get("traceId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


