# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_pagix_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from anvilkit_pagix_client.models.shared_primitives_v1_schema_reference import SharedPrimitivesV1SchemaReference
from anvilkit_pagix_client.models.tool_definition_v1_retry_policy import ToolDefinitionV1RetryPolicy
from anvilkit_pagix_client.models.tool_definition_v1_timeout_policy import ToolDefinitionV1TimeoutPolicy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ToolDefinitionV1(BaseModel):
    """
    Bounded ToolDefinitionV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    accepted_data_classes: Annotated[List[StrictStr], Field(min_length=1, max_length=4)] = Field(alias="acceptedDataClasses")
    api_version: Optional[Any] = Field(alias="apiVersion")
    approval_policy: SharedPrimitivesV1PolicyReference = Field(alias="approvalPolicy")
    capability: StrictStr
    capability_version: StrictStr = Field(alias="capabilityVersion")
    input_schema: SharedPrimitivesV1SchemaReference = Field(alias="inputSchema")
    kind: Optional[Any]
    output_schema: SharedPrimitivesV1SchemaReference = Field(alias="outputSchema")
    retry_policy: ToolDefinitionV1RetryPolicy = Field(alias="retryPolicy")
    risk_class: StrictStr = Field(alias="riskClass")
    side_effect_class: StrictStr = Field(alias="sideEffectClass")
    timeout_policy: ToolDefinitionV1TimeoutPolicy = Field(alias="timeoutPolicy")
    tool_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="toolId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["acceptedDataClasses", "apiVersion", "approvalPolicy", "capability", "capabilityVersion", "inputSchema", "kind", "outputSchema", "retryPolicy", "riskClass", "sideEffectClass", "timeoutPolicy", "toolId"]

    @field_validator('accepted_data_classes')
    def accepted_data_classes_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['public', 'internal', 'confidential', 'restricted']):
                raise ValueError("each list item must be one of ('public', 'internal', 'confidential', 'restricted')")
        return value

    @field_validator('capability')
    def capability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['provider.invoke', 'contract.validate', 'artifact.scan', 'fake.execute']):
            raise ValueError("must be one of enum values ('provider.invoke', 'contract.validate', 'artifact.scan', 'fake.execute')")
        return value

    @field_validator('capability_version')
    def capability_version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['provider.invoke/v1', 'contract.validate/v1', 'artifact.scan/v1', 'fake.execute/v1']):
            raise ValueError("must be one of enum values ('provider.invoke/v1', 'contract.validate/v1', 'artifact.scan/v1', 'fake.execute/v1')")
        return value

    @field_validator('risk_class')
    def risk_class_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['low', 'medium', 'high', 'critical']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'critical')")
        return value

    @field_validator('side_effect_class')
    def side_effect_class_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['none', 'read', 'artifact-write', 'domain-effect']):
            raise ValueError("must be one of enum values ('none', 'read', 'artifact-write', 'domain-effect')")
        return value

    @field_validator('tool_id')
    def tool_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolDefinitionV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of approval_policy
        if self.approval_policy:
            _dict['approvalPolicy'] = self.approval_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of input_schema
        if self.input_schema:
            _dict['inputSchema'] = self.input_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_schema
        if self.output_schema:
            _dict['outputSchema'] = self.output_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of retry_policy
        if self.retry_policy:
            _dict['retryPolicy'] = self.retry_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of timeout_policy
        if self.timeout_policy:
            _dict['timeoutPolicy'] = self.timeout_policy.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolDefinitionV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acceptedDataClasses": obj.get("acceptedDataClasses"),
            "apiVersion": obj.get("apiVersion"),
            "approvalPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["approvalPolicy"]) if obj.get("approvalPolicy") is not None else None,
            "capability": obj.get("capability"),
            "capabilityVersion": obj.get("capabilityVersion"),
            "inputSchema": SharedPrimitivesV1SchemaReference.from_dict(obj["inputSchema"]) if obj.get("inputSchema") is not None else None,
            "kind": obj.get("kind"),
            "outputSchema": SharedPrimitivesV1SchemaReference.from_dict(obj["outputSchema"]) if obj.get("outputSchema") is not None else None,
            "retryPolicy": ToolDefinitionV1RetryPolicy.from_dict(obj["retryPolicy"]) if obj.get("retryPolicy") is not None else None,
            "riskClass": obj.get("riskClass"),
            "sideEffectClass": obj.get("sideEffectClass"),
            "timeoutPolicy": ToolDefinitionV1TimeoutPolicy.from_dict(obj["timeoutPolicy"]) if obj.get("timeoutPolicy") is not None else None,
            "toolId": obj.get("toolId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


