# coding: utf-8

"""
    Pagix Agent Integration API

    Candidate internal Pagix integration contract for Agent workflows and governed effects.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkerLeaseV1(BaseModel):
    """
    Bounded WorkerLeaseV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    attempt_number: Annotated[int, Field(le=1000000, strict=True, ge=1)] = Field(alias="attemptNumber")
    execution_generation: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="executionGeneration")
    expires_at: datetime = Field(alias="expiresAt")
    fence_token: Annotated[str, Field(min_length=16, strict=True, max_length=512)] = Field(alias="fenceToken")
    issued_at: datetime = Field(alias="issuedAt")
    kind: Optional[Any]
    lease_epoch: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="leaseEpoch")
    owner: Annotated[str, Field(min_length=1, strict=True, max_length=128)]
    physical_attempt_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="physicalAttemptId")
    recovery_epoch: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="recoveryEpoch")
    task_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="taskId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "attemptNumber", "executionGeneration", "expiresAt", "fenceToken", "issuedAt", "kind", "leaseEpoch", "owner", "physicalAttemptId", "recoveryEpoch", "taskId"]

    @field_validator('expires_at')
    def expires_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('fence_token')
    def fence_token_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9._~-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9._~-]+$/")
        return value

    @field_validator('issued_at')
    def issued_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('owner')
    def owner_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('physical_attempt_id')
    def physical_attempt_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('task_id')
    def task_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkerLeaseV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkerLeaseV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "attemptNumber": obj.get("attemptNumber"),
            "executionGeneration": obj.get("executionGeneration"),
            "expiresAt": obj.get("expiresAt"),
            "fenceToken": obj.get("fenceToken"),
            "issuedAt": obj.get("issuedAt"),
            "kind": obj.get("kind"),
            "leaseEpoch": obj.get("leaseEpoch"),
            "owner": obj.get("owner"),
            "physicalAttemptId": obj.get("physicalAttemptId"),
            "recoveryEpoch": obj.get("recoveryEpoch"),
            "taskId": obj.get("taskId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


