# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.agent_task_v1_resources import AgentTaskV1Resources
from anvilkit_agent_client.models.shared_primitives_v1_artifact_reference import SharedPrimitivesV1ArtifactReference
from anvilkit_agent_client.models.shared_primitives_v1_contract_bom_reference_v1 import SharedPrimitivesV1ContractBomReferenceV1
from anvilkit_agent_client.models.shared_primitives_v1_idempotency import SharedPrimitivesV1Idempotency
from anvilkit_agent_client.models.shared_primitives_v1_resource_limits import SharedPrimitivesV1ResourceLimits
from anvilkit_agent_client.models.shared_primitives_v1_schema_reference import SharedPrimitivesV1SchemaReference
from anvilkit_agent_client.models.shared_primitives_v1_trace_context import SharedPrimitivesV1TraceContext
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentTaskV1(BaseModel):
    """
    Bounded AgentTaskV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    artifact_inputs: Annotated[List[SharedPrimitivesV1ArtifactReference], Field(min_length=0, max_length=32)] = Field(alias="artifactInputs")
    capability: StrictStr
    capability_version: StrictStr = Field(alias="capabilityVersion")
    contract_bom_reference: SharedPrimitivesV1ContractBomReferenceV1 = Field(alias="contractBomReference")
    execution_generation: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="executionGeneration")
    idempotency: SharedPrimitivesV1Idempotency
    input_schema_version: SharedPrimitivesV1SchemaReference = Field(alias="inputSchemaVersion")
    kind: Optional[Any]
    limits: SharedPrimitivesV1ResourceLimits
    parameters: Dict[str, Annotated[str, Field(min_length=0, strict=True, max_length=1024)]]
    resources: AgentTaskV1Resources
    root_run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="rootRunId")
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="runId")
    task_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="taskId")
    trace_context: SharedPrimitivesV1TraceContext = Field(alias="traceContext")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "artifactInputs", "capability", "capabilityVersion", "contractBomReference", "executionGeneration", "idempotency", "inputSchemaVersion", "kind", "limits", "parameters", "resources", "rootRunId", "runId", "taskId", "traceContext"]

    @field_validator('capability')
    def capability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['provider.invoke', 'contract.validate', 'artifact.scan', 'fake.execute']):
            raise ValueError("must be one of enum values ('provider.invoke', 'contract.validate', 'artifact.scan', 'fake.execute')")
        return value

    @field_validator('capability_version')
    def capability_version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['provider.invoke/v1', 'contract.validate/v1', 'artifact.scan/v1', 'fake.execute/v1']):
            raise ValueError("must be one of enum values ('provider.invoke/v1', 'contract.validate/v1', 'artifact.scan/v1', 'fake.execute/v1')")
        return value

    @field_validator('root_run_id')
    def root_run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('task_id')
    def task_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentTaskV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in artifact_inputs (list)
        _items = []
        if self.artifact_inputs:
            for _item_artifact_inputs in self.artifact_inputs:
                if _item_artifact_inputs:
                    _items.append(_item_artifact_inputs.to_dict())
            _dict['artifactInputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of contract_bom_reference
        if self.contract_bom_reference:
            _dict['contractBomReference'] = self.contract_bom_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of idempotency
        if self.idempotency:
            _dict['idempotency'] = self.idempotency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of input_schema_version
        if self.input_schema_version:
            _dict['inputSchemaVersion'] = self.input_schema_version.to_dict()
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trace_context
        if self.trace_context:
            _dict['traceContext'] = self.trace_context.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentTaskV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "artifactInputs": [SharedPrimitivesV1ArtifactReference.from_dict(_item) for _item in obj["artifactInputs"]] if obj.get("artifactInputs") is not None else None,
            "capability": obj.get("capability"),
            "capabilityVersion": obj.get("capabilityVersion"),
            "contractBomReference": SharedPrimitivesV1ContractBomReferenceV1.from_dict(obj["contractBomReference"]) if obj.get("contractBomReference") is not None else None,
            "executionGeneration": obj.get("executionGeneration"),
            "idempotency": SharedPrimitivesV1Idempotency.from_dict(obj["idempotency"]) if obj.get("idempotency") is not None else None,
            "inputSchemaVersion": SharedPrimitivesV1SchemaReference.from_dict(obj["inputSchemaVersion"]) if obj.get("inputSchemaVersion") is not None else None,
            "kind": obj.get("kind"),
            "limits": SharedPrimitivesV1ResourceLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "parameters": obj.get("parameters"),
            "resources": AgentTaskV1Resources.from_dict(obj["resources"]) if obj.get("resources") is not None else None,
            "rootRunId": obj.get("rootRunId"),
            "runId": obj.get("runId"),
            "taskId": obj.get("taskId"),
            "traceContext": SharedPrimitivesV1TraceContext.from_dict(obj["traceContext"]) if obj.get("traceContext") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


