# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.agent_definition_v1_tool_profile import AgentDefinitionV1ToolProfile
from anvilkit_agent_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from anvilkit_agent_client.models.shared_primitives_v1_schema_reference import SharedPrimitivesV1SchemaReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentDefinitionV1(BaseModel):
    """
    Bounded AgentDefinitionV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    definition_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="definitionId")
    domain: StrictStr
    evaluators: Annotated[List[SharedPrimitivesV1SchemaReference], Field(min_length=0, max_length=32)]
    guardrail_policy: SharedPrimitivesV1PolicyReference = Field(alias="guardrailPolicy")
    kind: Optional[Any]
    memory_policy: SharedPrimitivesV1PolicyReference = Field(alias="memoryPolicy")
    model_policy: SharedPrimitivesV1PolicyReference = Field(alias="modelPolicy")
    output_schema: SharedPrimitivesV1SchemaReference = Field(alias="outputSchema")
    prompt_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="promptDigest")
    stop_conditions: Annotated[List[StrictStr], Field(min_length=1, max_length=16)] = Field(alias="stopConditions")
    tool_profile: AgentDefinitionV1ToolProfile = Field(alias="toolProfile")
    turn_limit: Annotated[int, Field(le=1024, strict=True, ge=1)] = Field(alias="turnLimit")
    version: Annotated[str, Field(min_length=5, strict=True, max_length=32)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "definitionId", "domain", "evaluators", "guardrailPolicy", "kind", "memoryPolicy", "modelPolicy", "outputSchema", "promptDigest", "stopConditions", "toolProfile", "turnLimit", "version"]

    @field_validator('definition_id')
    def definition_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('domain')
    def domain_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['platform-agent', 'pagix-page', 'contract-runtime']):
            raise ValueError("must be one of enum values ('platform-agent', 'pagix-page', 'contract-runtime')")
        return value

    @field_validator('prompt_digest')
    def prompt_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('stop_conditions')
    def stop_conditions_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['completed', 'refused', 'budget-exhausted', 'approval-required', 'input-required', 'policy-blocked']):
                raise ValueError("each list item must be one of ('completed', 'refused', 'budget-exhausted', 'approval-required', 'input-required', 'policy-blocked')")
        return value

    @field_validator('version')
    def version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[1-9][0-9]*\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$", value):
            raise ValueError(r"must validate the regular expression /^[1-9][0-9]*\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentDefinitionV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in evaluators (list)
        _items = []
        if self.evaluators:
            for _item_evaluators in self.evaluators:
                if _item_evaluators:
                    _items.append(_item_evaluators.to_dict())
            _dict['evaluators'] = _items
        # override the default output from pydantic by calling `to_dict()` of guardrail_policy
        if self.guardrail_policy:
            _dict['guardrailPolicy'] = self.guardrail_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of memory_policy
        if self.memory_policy:
            _dict['memoryPolicy'] = self.memory_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of model_policy
        if self.model_policy:
            _dict['modelPolicy'] = self.model_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_schema
        if self.output_schema:
            _dict['outputSchema'] = self.output_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tool_profile
        if self.tool_profile:
            _dict['toolProfile'] = self.tool_profile.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentDefinitionV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "definitionId": obj.get("definitionId"),
            "domain": obj.get("domain"),
            "evaluators": [SharedPrimitivesV1SchemaReference.from_dict(_item) for _item in obj["evaluators"]] if obj.get("evaluators") is not None else None,
            "guardrailPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["guardrailPolicy"]) if obj.get("guardrailPolicy") is not None else None,
            "kind": obj.get("kind"),
            "memoryPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["memoryPolicy"]) if obj.get("memoryPolicy") is not None else None,
            "modelPolicy": SharedPrimitivesV1PolicyReference.from_dict(obj["modelPolicy"]) if obj.get("modelPolicy") is not None else None,
            "outputSchema": SharedPrimitivesV1SchemaReference.from_dict(obj["outputSchema"]) if obj.get("outputSchema") is not None else None,
            "promptDigest": obj.get("promptDigest"),
            "stopConditions": obj.get("stopConditions"),
            "toolProfile": AgentDefinitionV1ToolProfile.from_dict(obj["toolProfile"]) if obj.get("toolProfile") is not None else None,
            "turnLimit": obj.get("turnLimit"),
            "version": obj.get("version")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


