# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.agent_budget_v1 import AgentBudgetV1
from anvilkit_agent_client.models.problem_details_v1 import ProblemDetailsV1
from anvilkit_agent_client.models.shared_primitives_v1_contract_bom_reference_v1 import SharedPrimitivesV1ContractBomReferenceV1
from anvilkit_agent_client.models.shared_primitives_v1_idempotency import SharedPrimitivesV1Idempotency
from anvilkit_agent_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from anvilkit_agent_client.models.shared_primitives_v1_target_reference import SharedPrimitivesV1TargetReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentRunV1(BaseModel):
    """
    Bounded AgentRunV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    actor_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="actorId")
    api_version: Optional[Any] = Field(alias="apiVersion")
    budget: AgentBudgetV1
    contract_bom_reference: SharedPrimitivesV1ContractBomReferenceV1 = Field(alias="contractBomReference")
    created_at: datetime = Field(alias="createdAt")
    domain: StrictStr
    execution_generation: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="executionGeneration")
    idempotency: SharedPrimitivesV1Idempotency
    kind: Optional[Any]
    operation: StrictStr
    parent_run_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = Field(default=None, alias="parentRunId")
    policy: SharedPrimitivesV1PolicyReference
    problem: Optional[ProblemDetailsV1] = None
    root_run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="rootRunId")
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="runId")
    status: StrictStr
    target: SharedPrimitivesV1TargetReference
    tenant_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="tenantId")
    updated_at: datetime = Field(alias="updatedAt")
    workspace_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="workspaceId")
    __properties: ClassVar[List[str]] = ["actorId", "apiVersion", "budget", "contractBomReference", "createdAt", "domain", "executionGeneration", "idempotency", "kind", "operation", "parentRunId", "policy", "problem", "rootRunId", "runId", "status", "target", "tenantId", "updatedAt", "workspaceId"]

    @field_validator('actor_id')
    def actor_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('created_at')
    def created_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('domain')
    def domain_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['platform-agent', 'pagix-page', 'contract-runtime']):
            raise ValueError("must be one of enum values ('platform-agent', 'pagix-page', 'contract-runtime')")
        return value

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['page-change', 'artifact-validation', 'image-operation', 'component-package']):
            raise ValueError("must be one of enum values ('page-change', 'artifact-validation', 'image-operation', 'component-package')")
        return value

    @field_validator('parent_run_id')
    def parent_run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('root_run_id')
    def root_run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['created', 'preparing', 'planning', 'awaiting_input', 'executing', 'validating', 'awaiting_review', 'awaiting_approval', 'committing', 'awaiting_domain_confirmation', 'conflict', 'cancelling', 'failed', 'completed', 'cancelled', 'refused', 'discarded']):
            raise ValueError("must be one of enum values ('created', 'preparing', 'planning', 'awaiting_input', 'executing', 'validating', 'awaiting_review', 'awaiting_approval', 'committing', 'awaiting_domain_confirmation', 'conflict', 'cancelling', 'failed', 'completed', 'cancelled', 'refused', 'discarded')")
        return value

    @field_validator('tenant_id')
    def tenant_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('updated_at')
    def updated_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('workspace_id')
    def workspace_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentRunV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contract_bom_reference
        if self.contract_bom_reference:
            _dict['contractBomReference'] = self.contract_bom_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of idempotency
        if self.idempotency:
            _dict['idempotency'] = self.idempotency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of problem
        if self.problem:
            _dict['problem'] = self.problem.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentRunV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actorId": obj.get("actorId"),
            "apiVersion": obj.get("apiVersion"),
            "budget": AgentBudgetV1.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "contractBomReference": SharedPrimitivesV1ContractBomReferenceV1.from_dict(obj["contractBomReference"]) if obj.get("contractBomReference") is not None else None,
            "createdAt": obj.get("createdAt"),
            "domain": obj.get("domain"),
            "executionGeneration": obj.get("executionGeneration"),
            "idempotency": SharedPrimitivesV1Idempotency.from_dict(obj["idempotency"]) if obj.get("idempotency") is not None else None,
            "kind": obj.get("kind"),
            "operation": obj.get("operation"),
            "parentRunId": obj.get("parentRunId"),
            "policy": SharedPrimitivesV1PolicyReference.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "problem": ProblemDetailsV1.from_dict(obj["problem"]) if obj.get("problem") is not None else None,
            "rootRunId": obj.get("rootRunId"),
            "runId": obj.get("runId"),
            "status": obj.get("status"),
            "target": SharedPrimitivesV1TargetReference.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "tenantId": obj.get("tenantId"),
            "updatedAt": obj.get("updatedAt"),
            "workspaceId": obj.get("workspaceId")
        })
        return _obj


