# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.shared_primitives_v1_target_reference import SharedPrimitivesV1TargetReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApplyAuthorizationV1(BaseModel):
    """
    Bounded ApplyAuthorizationV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    action_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="actionDigest")
    actor_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="actorId")
    api_version: Optional[Any] = Field(alias="apiVersion")
    approval_version: Annotated[int, Field(le=9007199254740991, strict=True, ge=1)] = Field(alias="approvalVersion")
    artifact_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="artifactDigest")
    audience: Optional[Any]
    authorization_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="authorizationId")
    base_revision: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="baseRevision")
    contract_bom_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="contractBomDigest")
    expires_at: datetime = Field(alias="expiresAt")
    issued_at: datetime = Field(alias="issuedAt")
    issuer: Optional[Any]
    key_id: Annotated[str, Field(min_length=16, strict=True, max_length=256)] = Field(alias="keyId")
    kind: Optional[Any]
    not_before: datetime = Field(alias="notBefore")
    policy_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="policyDigest")
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="runId")
    target: SharedPrimitivesV1TargetReference
    workspace_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="workspaceId")
    __properties: ClassVar[List[str]] = ["actionDigest", "actorId", "apiVersion", "approvalVersion", "artifactDigest", "audience", "authorizationId", "baseRevision", "contractBomDigest", "expiresAt", "issuedAt", "issuer", "keyId", "kind", "notBefore", "policyDigest", "runId", "target", "workspaceId"]

    @field_validator('action_digest')
    def action_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('actor_id')
    def actor_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('artifact_digest')
    def artifact_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('authorization_id')
    def authorization_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('base_revision')
    def base_revision_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('contract_bom_digest')
    def contract_bom_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('expires_at')
    def expires_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('issued_at')
    def issued_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('key_id')
    def key_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^urn:anvilkit:key:[a-z0-9][a-z0-9:-]*$", value):
            raise ValueError(r"must validate the regular expression /^urn:anvilkit:key:[a-z0-9][a-z0-9:-]*$/")
        return value

    @field_validator('not_before')
    def not_before_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('policy_digest')
    def policy_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('workspace_id')
    def workspace_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplyAuthorizationV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if audience (nullable) is None
        # and model_fields_set contains the field
        if self.audience is None and "audience" in self.model_fields_set:
            _dict['audience'] = None

        # set to None if issuer (nullable) is None
        # and model_fields_set contains the field
        if self.issuer is None and "issuer" in self.model_fields_set:
            _dict['issuer'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplyAuthorizationV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actionDigest": obj.get("actionDigest"),
            "actorId": obj.get("actorId"),
            "apiVersion": obj.get("apiVersion"),
            "approvalVersion": obj.get("approvalVersion"),
            "artifactDigest": obj.get("artifactDigest"),
            "audience": obj.get("audience"),
            "authorizationId": obj.get("authorizationId"),
            "baseRevision": obj.get("baseRevision"),
            "contractBomDigest": obj.get("contractBomDigest"),
            "expiresAt": obj.get("expiresAt"),
            "issuedAt": obj.get("issuedAt"),
            "issuer": obj.get("issuer"),
            "keyId": obj.get("keyId"),
            "kind": obj.get("kind"),
            "notBefore": obj.get("notBefore"),
            "policyDigest": obj.get("policyDigest"),
            "runId": obj.get("runId"),
            "target": SharedPrimitivesV1TargetReference.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "workspaceId": obj.get("workspaceId")
        })
        return _obj


