# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.compiled_context_v1_ordered_trust_layers_inner import CompiledContextV1OrderedTrustLayersInner
from anvilkit_agent_client.models.compiled_context_v1_redaction import CompiledContextV1Redaction
from anvilkit_agent_client.models.compiled_context_v1_token_budgets import CompiledContextV1TokenBudgets
from anvilkit_agent_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompiledContextV1(BaseModel):
    """
    Bounded CompiledContextV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    classifications: Annotated[List[StrictStr], Field(min_length=1, max_length=4)]
    compiled_at: datetime = Field(alias="compiledAt")
    kind: Optional[Any]
    layer_digests: Annotated[List[Annotated[str, Field(min_length=71, strict=True, max_length=71)]], Field(min_length=1, max_length=128)] = Field(alias="layerDigests")
    ordered_trust_layers: Annotated[List[CompiledContextV1OrderedTrustLayersInner], Field(min_length=1, max_length=128)] = Field(alias="orderedTrustLayers")
    policy_snapshot: SharedPrimitivesV1PolicyReference = Field(alias="policySnapshot")
    redaction: CompiledContextV1Redaction
    token_budgets: CompiledContextV1TokenBudgets = Field(alias="tokenBudgets")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "classifications", "compiledAt", "kind", "layerDigests", "orderedTrustLayers", "policySnapshot", "redaction", "tokenBudgets"]

    @field_validator('classifications')
    def classifications_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['public', 'internal', 'confidential', 'restricted']):
                raise ValueError("each list item must be one of ('public', 'internal', 'confidential', 'restricted')")
        return value

    @field_validator('compiled_at')
    def compiled_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompiledContextV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ordered_trust_layers (list)
        _items = []
        if self.ordered_trust_layers:
            for _item_ordered_trust_layers in self.ordered_trust_layers:
                if _item_ordered_trust_layers:
                    _items.append(_item_ordered_trust_layers.to_dict())
            _dict['orderedTrustLayers'] = _items
        # override the default output from pydantic by calling `to_dict()` of policy_snapshot
        if self.policy_snapshot:
            _dict['policySnapshot'] = self.policy_snapshot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of redaction
        if self.redaction:
            _dict['redaction'] = self.redaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of token_budgets
        if self.token_budgets:
            _dict['tokenBudgets'] = self.token_budgets.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompiledContextV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "classifications": obj.get("classifications"),
            "compiledAt": obj.get("compiledAt"),
            "kind": obj.get("kind"),
            "layerDigests": obj.get("layerDigests"),
            "orderedTrustLayers": [CompiledContextV1OrderedTrustLayersInner.from_dict(_item) for _item in obj["orderedTrustLayers"]] if obj.get("orderedTrustLayers") is not None else None,
            "policySnapshot": SharedPrimitivesV1PolicyReference.from_dict(obj["policySnapshot"]) if obj.get("policySnapshot") is not None else None,
            "redaction": CompiledContextV1Redaction.from_dict(obj["redaction"]) if obj.get("redaction") is not None else None,
            "tokenBudgets": CompiledContextV1TokenBudgets.from_dict(obj["tokenBudgets"]) if obj.get("tokenBudgets") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


