# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.contract_revocation_snapshot_v1_revoked_keys_inner import ContractRevocationSnapshotV1RevokedKeysInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ContractRevocationSnapshotV1(BaseModel):
    """
    Signed fail-closed key revocation snapshot with explicit freshness.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    issued_at: datetime = Field(alias="issuedAt")
    kind: Optional[Any]
    next_update: datetime = Field(alias="nextUpdate")
    revoked_keys: Annotated[List[ContractRevocationSnapshotV1RevokedKeysInner], Field(min_length=0, max_length=10000)] = Field(alias="revokedKeys")
    snapshot_id: Annotated[str, Field(min_length=16, strict=True, max_length=128)] = Field(alias="snapshotId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "issuedAt", "kind", "nextUpdate", "revokedKeys", "snapshotId"]

    @field_validator('issued_at')
    def issued_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('next_update')
    def next_update_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('snapshot_id')
    def snapshot_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z0-9][a-z0-9:-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9][a-z0-9:-]*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractRevocationSnapshotV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in revoked_keys (list)
        _items = []
        if self.revoked_keys:
            for _item_revoked_keys in self.revoked_keys:
                if _item_revoked_keys:
                    _items.append(_item_revoked_keys.to_dict())
            _dict['revokedKeys'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractRevocationSnapshotV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "issuedAt": obj.get("issuedAt"),
            "kind": obj.get("kind"),
            "nextUpdate": obj.get("nextUpdate"),
            "revokedKeys": [ContractRevocationSnapshotV1RevokedKeysInner.from_dict(_item) for _item in obj["revokedKeys"]] if obj.get("revokedKeys") is not None else None,
            "snapshotId": obj.get("snapshotId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


