# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SharedPrimitivesV1ContractBomReferenceV1(BaseModel):
    """
    SharedPrimitivesV1ContractBomReferenceV1
    """ # noqa: E501
    bom_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="bomDigest")
    evidence_manifest_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="evidenceManifestDigest")
    oci_manifest_digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="ociManifestDigest")
    repository: Annotated[str, Field(min_length=1, strict=True, max_length=256)]
    __properties: ClassVar[List[str]] = ["bomDigest", "evidenceManifestDigest", "ociManifestDigest", "repository"]

    @field_validator('bom_digest')
    def bom_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('evidence_manifest_digest')
    def evidence_manifest_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('oci_manifest_digest')
    def oci_manifest_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('repository')
    def repository_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z0-9][a-z0-9._\/-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9][a-z0-9._\/-]*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedPrimitivesV1ContractBomReferenceV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedPrimitivesV1ContractBomReferenceV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bomDigest": obj.get("bomDigest"),
            "evidenceManifestDigest": obj.get("evidenceManifestDigest"),
            "ociManifestDigest": obj.get("ociManifestDigest"),
            "repository": obj.get("repository")
        })
        return _obj


