# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from anvilkit_agent_client.models.shared_primitives_v1_artifact_reference import SharedPrimitivesV1ArtifactReference
from anvilkit_agent_client.models.shared_primitives_v1_contract_bom_reference_v1 import SharedPrimitivesV1ContractBomReferenceV1
from anvilkit_agent_client.models.shared_primitives_v1_cost import SharedPrimitivesV1Cost
from anvilkit_agent_client.models.shared_primitives_v1_idempotency import SharedPrimitivesV1Idempotency
from anvilkit_agent_client.models.shared_primitives_v1_page_info import SharedPrimitivesV1PageInfo
from anvilkit_agent_client.models.shared_primitives_v1_policy_reference import SharedPrimitivesV1PolicyReference
from anvilkit_agent_client.models.shared_primitives_v1_resource_limits import SharedPrimitivesV1ResourceLimits
from anvilkit_agent_client.models.shared_primitives_v1_schema_reference import SharedPrimitivesV1SchemaReference
from anvilkit_agent_client.models.shared_primitives_v1_target_reference import SharedPrimitivesV1TargetReference
from anvilkit_agent_client.models.shared_primitives_v1_trace_and_scope import SharedPrimitivesV1TraceAndScope
from anvilkit_agent_client.models.shared_primitives_v1_trace_context import SharedPrimitivesV1TraceContext
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SharedPrimitivesV1DefinitionSet(BaseModel):
    """
    SharedPrimitivesV1DefinitionSet
    """ # noqa: E501
    actor_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="ActorId")
    artifact_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="ArtifactId")
    artifact_reference: SharedPrimitivesV1ArtifactReference = Field(alias="ArtifactReference")
    authorization_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="AuthorizationId")
    bounded_string_map: Dict[str, Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(alias="BoundedStringMap")
    build_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="BuildId")
    contract_bom_reference_v1: SharedPrimitivesV1ContractBomReferenceV1 = Field(alias="ContractBomReferenceV1")
    cost: SharedPrimitivesV1Cost = Field(alias="Cost")
    cursor: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(alias="Cursor")
    decimal_string: Annotated[str, Field(min_length=1, strict=True, max_length=96)] = Field(alias="DecimalString")
    digest: Annotated[str, Field(min_length=71, strict=True, max_length=71)] = Field(alias="Digest")
    idempotency: SharedPrimitivesV1Idempotency = Field(alias="Idempotency")
    integer_string: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(alias="IntegerString")
    opaque_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="OpaqueId")
    page_info: SharedPrimitivesV1PageInfo = Field(alias="PageInfo")
    physical_attempt_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="PhysicalAttemptId")
    policy_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="PolicyId")
    policy_reference: SharedPrimitivesV1PolicyReference = Field(alias="PolicyReference")
    request_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="RequestId")
    reservation_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="ReservationId")
    resource_limits: SharedPrimitivesV1ResourceLimits = Field(alias="ResourceLimits")
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="RunId")
    schema_reference: SharedPrimitivesV1SchemaReference = Field(alias="SchemaReference")
    target_reference: SharedPrimitivesV1TargetReference = Field(alias="TargetReference")
    task_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="TaskId")
    tenant_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="TenantId")
    timestamp: datetime = Field(alias="Timestamp")
    trace_and_scope: SharedPrimitivesV1TraceAndScope = Field(alias="TraceAndScope")
    trace_context: SharedPrimitivesV1TraceContext = Field(alias="TraceContext")
    workspace_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="WorkspaceId")
    __properties: ClassVar[List[str]] = ["ActorId", "ArtifactId", "ArtifactReference", "AuthorizationId", "BoundedStringMap", "BuildId", "ContractBomReferenceV1", "Cost", "Cursor", "DecimalString", "Digest", "Idempotency", "IntegerString", "OpaqueId", "PageInfo", "PhysicalAttemptId", "PolicyId", "PolicyReference", "RequestId", "ReservationId", "ResourceLimits", "RunId", "SchemaReference", "TargetReference", "TaskId", "TenantId", "Timestamp", "TraceAndScope", "TraceContext", "WorkspaceId"]

    @field_validator('actor_id')
    def actor_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('artifact_id')
    def artifact_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('authorization_id')
    def authorization_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('build_id')
    def build_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('cursor')
    def cursor_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9._~-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9._~-]+$/")
        return value

    @field_validator('decimal_string')
    def decimal_string_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^-?(0|[1-9][0-9]*)(\.[0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?(0|[1-9][0-9]*)(\.[0-9]+)?$/")
        return value

    @field_validator('digest')
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('integer_string')
    def integer_string_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^-?(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^-?(0|[1-9][0-9]*)$/")
        return value

    @field_validator('opaque_id')
    def opaque_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('physical_attempt_id')
    def physical_attempt_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('policy_id')
    def policy_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('request_id')
    def request_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('reservation_id')
    def reservation_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('task_id')
    def task_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('tenant_id')
    def tenant_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('timestamp')
    def timestamp_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('workspace_id')
    def workspace_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedPrimitivesV1DefinitionSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of artifact_reference
        if self.artifact_reference:
            _dict['ArtifactReference'] = self.artifact_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contract_bom_reference_v1
        if self.contract_bom_reference_v1:
            _dict['ContractBomReferenceV1'] = self.contract_bom_reference_v1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['Cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of idempotency
        if self.idempotency:
            _dict['Idempotency'] = self.idempotency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of page_info
        if self.page_info:
            _dict['PageInfo'] = self.page_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy_reference
        if self.policy_reference:
            _dict['PolicyReference'] = self.policy_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resource_limits
        if self.resource_limits:
            _dict['ResourceLimits'] = self.resource_limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of schema_reference
        if self.schema_reference:
            _dict['SchemaReference'] = self.schema_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target_reference
        if self.target_reference:
            _dict['TargetReference'] = self.target_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trace_and_scope
        if self.trace_and_scope:
            _dict['TraceAndScope'] = self.trace_and_scope.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trace_context
        if self.trace_context:
            _dict['TraceContext'] = self.trace_context.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedPrimitivesV1DefinitionSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ActorId": obj.get("ActorId"),
            "ArtifactId": obj.get("ArtifactId"),
            "ArtifactReference": SharedPrimitivesV1ArtifactReference.from_dict(obj["ArtifactReference"]) if obj.get("ArtifactReference") is not None else None,
            "AuthorizationId": obj.get("AuthorizationId"),
            "BoundedStringMap": obj.get("BoundedStringMap"),
            "BuildId": obj.get("BuildId"),
            "ContractBomReferenceV1": SharedPrimitivesV1ContractBomReferenceV1.from_dict(obj["ContractBomReferenceV1"]) if obj.get("ContractBomReferenceV1") is not None else None,
            "Cost": SharedPrimitivesV1Cost.from_dict(obj["Cost"]) if obj.get("Cost") is not None else None,
            "Cursor": obj.get("Cursor"),
            "DecimalString": obj.get("DecimalString"),
            "Digest": obj.get("Digest"),
            "Idempotency": SharedPrimitivesV1Idempotency.from_dict(obj["Idempotency"]) if obj.get("Idempotency") is not None else None,
            "IntegerString": obj.get("IntegerString"),
            "OpaqueId": obj.get("OpaqueId"),
            "PageInfo": SharedPrimitivesV1PageInfo.from_dict(obj["PageInfo"]) if obj.get("PageInfo") is not None else None,
            "PhysicalAttemptId": obj.get("PhysicalAttemptId"),
            "PolicyId": obj.get("PolicyId"),
            "PolicyReference": SharedPrimitivesV1PolicyReference.from_dict(obj["PolicyReference"]) if obj.get("PolicyReference") is not None else None,
            "RequestId": obj.get("RequestId"),
            "ReservationId": obj.get("ReservationId"),
            "ResourceLimits": SharedPrimitivesV1ResourceLimits.from_dict(obj["ResourceLimits"]) if obj.get("ResourceLimits") is not None else None,
            "RunId": obj.get("RunId"),
            "SchemaReference": SharedPrimitivesV1SchemaReference.from_dict(obj["SchemaReference"]) if obj.get("SchemaReference") is not None else None,
            "TargetReference": SharedPrimitivesV1TargetReference.from_dict(obj["TargetReference"]) if obj.get("TargetReference") is not None else None,
            "TaskId": obj.get("TaskId"),
            "TenantId": obj.get("TenantId"),
            "Timestamp": obj.get("Timestamp"),
            "TraceAndScope": SharedPrimitivesV1TraceAndScope.from_dict(obj["TraceAndScope"]) if obj.get("TraceAndScope") is not None else None,
            "TraceContext": SharedPrimitivesV1TraceContext.from_dict(obj["TraceContext"]) if obj.get("TraceContext") is not None else None,
            "WorkspaceId": obj.get("WorkspaceId")
        })
        return _obj


