# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ToolDefinitionV1RetryPolicy(BaseModel):
    """
    ToolDefinitionV1RetryPolicy
    """ # noqa: E501
    backoff_milliseconds: Annotated[int, Field(le=3600000, strict=True, ge=0)] = Field(alias="backoffMilliseconds")
    maximum_attempts: Annotated[int, Field(le=100, strict=True, ge=1)] = Field(alias="maximumAttempts")
    retryability: Annotated[List[StrictStr], Field(min_length=0, max_length=3)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["backoffMilliseconds", "maximumAttempts", "retryability"]

    @field_validator('retryability')
    def retryability_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['safe-immediate', 'safe-after-backoff', 'operator-action']):
                raise ValueError("each list item must be one of ('safe-immediate', 'safe-after-backoff', 'operator-action')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolDefinitionV1RetryPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolDefinitionV1RetryPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backoffMilliseconds": obj.get("backoffMilliseconds"),
            "maximumAttempts": obj.get("maximumAttempts"),
            "retryability": obj.get("retryability")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


