# coding: utf-8

"""
    AnvilKit Agent Service API

    Candidate P0 Agent Service HTTP contract. JSON Schema components remain authoritative.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from anvilkit_agent_client.models.shared_primitives_v1_cost import SharedPrimitivesV1Cost
from anvilkit_agent_client.models.shared_primitives_v1_trace_context import SharedPrimitivesV1TraceContext
from anvilkit_agent_client.models.usage_observation_v1_source import UsageObservationV1Source
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UsageObservationV1(BaseModel):
    """
    Bounded UsageObservationV1 wire contract governed by PRD 0012.
    """ # noqa: E501
    api_version: Optional[Any] = Field(alias="apiVersion")
    cost: SharedPrimitivesV1Cost
    execution_generation: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="executionGeneration")
    final: StrictBool
    kind: Optional[Any]
    meter: StrictStr
    meter_sequence: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="meterSequence")
    observation_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="observationId")
    observed_at: datetime = Field(alias="observedAt")
    physical_attempt_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="physicalAttemptId")
    provider_event_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=128)]] = Field(default=None, alias="providerEventId")
    quantity: Annotated[str, Field(min_length=1, strict=True, max_length=96)]
    recovery_epoch: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="recoveryEpoch")
    reservation_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="reservationId")
    root_run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="rootRunId")
    run_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="runId")
    source: UsageObservationV1Source
    task_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(alias="taskId")
    trace_context: SharedPrimitivesV1TraceContext = Field(alias="traceContext")
    unit: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiVersion", "cost", "executionGeneration", "final", "kind", "meter", "meterSequence", "observationId", "observedAt", "physicalAttemptId", "providerEventId", "quantity", "recoveryEpoch", "reservationId", "rootRunId", "runId", "source", "taskId", "traceContext", "unit"]

    @field_validator('meter')
    def meter_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['input-tokens', 'output-tokens', 'worker-duration', 'gpu-duration', 'provider-cost']):
            raise ValueError("must be one of enum values ('input-tokens', 'output-tokens', 'worker-duration', 'gpu-duration', 'provider-cost')")
        return value

    @field_validator('observation_id')
    def observation_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('observed_at')
    def observed_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/")
        return value

    @field_validator('physical_attempt_id')
    def physical_attempt_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('provider_event_id')
    def provider_event_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('quantity')
    def quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^-?(0|[1-9][0-9]*)(\.[0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?(0|[1-9][0-9]*)(\.[0-9]+)?$/")
        return value

    @field_validator('reservation_id')
    def reservation_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('root_run_id')
    def root_run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('run_id')
    def run_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('task_id')
    def task_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/")
        return value

    @field_validator('unit')
    def unit_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['token', 'millisecond', 'byte', 'count', 'usd-micro']):
            raise ValueError("must be one of enum values ('token', 'millisecond', 'byte', 'count', 'usd-micro')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageObservationV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trace_context
        if self.trace_context:
            _dict['traceContext'] = self.trace_context.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_version (nullable) is None
        # and model_fields_set contains the field
        if self.api_version is None and "api_version" in self.model_fields_set:
            _dict['apiVersion'] = None

        # set to None if kind (nullable) is None
        # and model_fields_set contains the field
        if self.kind is None and "kind" in self.model_fields_set:
            _dict['kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageObservationV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "cost": SharedPrimitivesV1Cost.from_dict(obj["cost"]) if obj.get("cost") is not None else None,
            "executionGeneration": obj.get("executionGeneration"),
            "final": obj.get("final"),
            "kind": obj.get("kind"),
            "meter": obj.get("meter"),
            "meterSequence": obj.get("meterSequence"),
            "observationId": obj.get("observationId"),
            "observedAt": obj.get("observedAt"),
            "physicalAttemptId": obj.get("physicalAttemptId"),
            "providerEventId": obj.get("providerEventId"),
            "quantity": obj.get("quantity"),
            "recoveryEpoch": obj.get("recoveryEpoch"),
            "reservationId": obj.get("reservationId"),
            "rootRunId": obj.get("rootRunId"),
            "runId": obj.get("runId"),
            "source": UsageObservationV1Source.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "taskId": obj.get("taskId"),
            "traceContext": SharedPrimitivesV1TraceContext.from_dict(obj["traceContext"]) if obj.get("traceContext") is not None else None,
            "unit": obj.get("unit")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


